<?php

use Illuminate\Database\Seeder;
use App\Distrito;
class DistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $distritos = array(
            "1"=>array('Asuncion',
                        'Balsas',
                        'Chachapoyas',
                        'Cheto',
                        'Chiliquin',
                        'Chuquibamba',
                        'Granada',
                        'Huancas',
                        'La Jalca',
                        'Levanto',
                        'Leymebamba',
                        'Magdalena',
                        'Mariscal Castilla',
                        'Molinopampa',
                        'Montevideo',
                        'Olleros',
                        'Quinjalca',
                        'San Francisco de Daguas',
                        'San Isidro de Maino',
                        'Soloco',
                        'Sonche'),
            "2"=>array('Aramango',
                        'Bagua',
                        'Copallin',
                        'El Parco',
                        'Imaza',
                        'La Peca'),
            "3"=>array('Chisquilla',
                        'Churuja',
                        'Corosha',
                        'Cuispes',
                        'Florida',
                        'Jazan',
                        'Jumbilla',
                        'Recta',
                        'San Carlos',
                        'Shipasbamba',
                        'Valera',
                        'Yambrasbamba'),
            "4"=>array('El Cenepa',
                        'Nieva',
                        'Rio Santiago'),
            "5"=>array('Camporredondo',
                        'Cocabamba',
                        'Colcamar',
                        'Conila',
                        'Inguilpata',
                        'Lamud',
                        'Longuita',
                        'Lonya Chico',
                        'Luya',
                        'Luya Viejo',
                        'María',
                        'Ocalli',
                        'Ocumal',
                        'Pisuquia',
                        'Providencia',
                        'San Cristóbal',
                        'San Francisco del Yeso',
                        'San Jerónimo',
                        'San Juan de Lopecancha',
                        'Santa Catalina',
                        'Santo Tomás',
                        'Tingo',
                        'Trita'),
            "6"=>array('Chirimoto',
                        'Cochamal',
                        'Huambo',
                        'Limabamba',
                        'Longar',
                        'Mariscal Benavides',
                        'Milpuc',
                        'Omia',
                        'San Nicolás',
                        'Santa Rosa',
                        'Totora',
                        'Vista Alegre'),
            "7"=>array('Bagua Grande',
                        'Cajaruro',
                        'Cumba',
                        'El Milagro',
                        'Jamalca',
                        'Lonya Grande',
                        'Yamon'),
            "8"=>array('Aji',
                        'Coris',
                        'Huacllan',
                        'La Merced',
                        'Succha'),
            "9"=>array('Aczo',
                        'Chaccho',
                        'Chingas',
                        'Llamellin',
                        'Mirgas',
                        'San Juan De Rontoy'),
            "10"=>array('Acochaca',
                        'Chacas'),
            "11"=>array('Abelardo Pardo Lezameta',
                        'Antonio Raymondi',
                        'Aquia',
                        'Cajacay',
                        'Canis',
                        'Chiquian',
                        'Colquioc',
                        'Huallanca',
                        'Huasta',
                        'Huayllacayan',
                        'La Primavera',
                        'Mangas',
                        'Pacllón',
                        'San Miguel De Corpanqui',
                        'Ticllos'),
            "12"=>array('Acopampa',
                        'Amashca',
                        'Anta',
                        'Ataquero',
                        'Carhuaz',
                        'Marcará',
                        'Parihuanca',
                        'San Miguel De Aco',
                        'Shilla',
                        'Tinco',
                        'Yungar'),
            "13"=>array('San Luis',
                        'San Nicolás',
                        'Yauya'),
            "14"=>array('Buena Vista Alta',
                        'Casma',
                        'Comandante Noel',
                        'Yaután'),
            "15"=>array('Aco',
                        'Bambas',
                        'Corongo',
                        'Cusca',
                        'La Pampa',
                        'Yanac',
                        'Yupan'),
            "16"=>array('Cochabamba',
                        'Colcabamba',
                        'Huanchay',
                        'Huaraz',
                        'Independencia',
                        'Jangas',
                        'La Libertad',
                        'Olleros',
                        'Pampas',
                        'Pariacoto',
                        'Pira',
                        'Tarica'),
            "17"=>array('Anra',
                        'Cajay',
                        'Chavín de Huantar',
                        'Huacachi',
                        'Huacchis',
                        'Huachis',
                        'Huantar',
                        'Huari',
                        'Masin',
                        'Paucas',
                        'Pontó',
                        'Rahuapampa',
                        'Rapayán',
                        'San Marcos',
                        'San Pedro de Chaná',
                        'Uco'),
            "18"=>array('Cochapeti',
                        'Culebras',
                        'Huarmey',
                        'Huayan',
                        'Malvas'),
            "19"=>array('Caraz',
                        'Huallanca',
                        'Huata',
                        'Huaylas',
                        'Mato',
                        'Pamparomas',
                        'Pueblo Libre',
                        'Santa Cruz',
                        'Santo Toribio',
                        'Yuracmarca'),
            "20"=>array('Casca',
                        'Eleazar Guzmán Barrón',
                        'Fidel Olivas Escudero',
                        'Llama',
                        'Llumpa',
                        'Lucma',
                        'Musga',
                        'Piscobamba'),
            "21"=>array('Acas',
                        'Cajamarquilla',
                        'Carhuapampa',
                        'Cochas',
                        'Congas',
                        'Llipa',
                        'Ocros',
                        'San Cristobal de Rajan',
                        'San Pedro',
                        'Santiago de Chilcas'),
            "22"=>array('Bolognesi',
                        'Cabana',
                        'Conchucos',
                        'Huacaschuque',
                        'Huandoval',
                        'Lacabamba',
                        'Llapo',
                        'Pallasca',
                        'Pampas',
                        'Santa Rosa',
                        'Tauca'),
            "23"=>array('Huayllán',
                        'Parobamba',
                        'Pomabamba',
                        'Quinuabamba'),
            "24"=>array('Catác',
                        'Cotaparaco',
                        'Huayllapampa',
                        'Llacllin',
                        'Marca',
                        'Pampas Chico',
                        'Pararin',
                        'Recuay',
                        'Tapacocha',
                        'Ticapampa'),
            "25"=>array('Cáceres del Perú',
                        'Chimbote',
                        'Coishco',
                        'Macate',
                        'Moro',
                        'Nepeña',
                        'Nuevo Chimbote',
                        'Samanco',
                        'Santa'),
            "26"=>array('Acobamba',
                        'Alfonso Ugarte',
                        'Cashapampa',
                        'Chingalpo',
                        'Huayllabamba',
                        'Quiches',
                        'Ragash',
                        'San Juan',
                        'Sicsibamba',
                        'Sihuas'),
            "27"=>array('Cascapara',
                        'Mancos',
                        'Matacoto',
                        'Quillo',
                        'Ranrahirca',
                        'Shupluy',
                        'Yanama',
                        'Yungay'),
            "28"=>array('Abancay',
                        'Chacoche',
                        'Circa',
                        'Curahuasi',
                        'Huanipaca',
                        'Lambrama',
                        'Pichirhua',
                        'San Pedro de Cachora',
                        'Tamburco'),
            "29"=>array('Andahuaylas',
                        'Andarapa',
                        'Chiara',
                        'Huancarama',
                        'Huancaray',
                        'Huayana',
                        'Kaquiabamba',
                        'Kishuara',
                        'Pacobamba',
                        'Pacucha',
                        'Pampachiri',
                        'Pomacocha',
                        'San Antonio de Cachi',
                        'San Jerónimo',
                        'San Miguel De Chaccrampa',
                        'Santa María de Chicmo',
                        'Talavera de la Reina',
                        'Tumay Huaraca',
                        'Turpo'),
            "30"=>array('Antabamba',
                        'El Oro',
                        'Huaquirca',
                        'Juan Espinoza Medrano',
                        'Oropesa',
                        'Pachaconas',
                        'Sabaino'),
            "31"=>array('Capaya',
                        'Caraybamba',
                        'Chalhuanca',
                        'Chapimarca',
                        'Colcabamba',
                        'Cotaruse',
                        'Huayllo',
                        'Justo Apu Sahuaraura',
                        'Lucre',
                        'Pocohuanca',
                        'San Juan de Chacña',
                        'Sañayca',
                        'Soraya',
                        'Tapahirihua',
                        'Tintay',
                        'Toraya',
                        'Yanaca'),
            "32"=>array('Anccohuayllo',
                        'Chincheros',
                        'Cocharcas',
                        'Huaccana',
                        'Ocobamba',
                        'Ongoy',
                        'Ranracancha',
                        'Uranmarca'),
            "33"=>array('Challhuahuacho',
                        'Cotabambas',
                        'Coyllurqui',
                        'Haquira',
                        'Mara',
                        'Tambobamba'),
            "34"=>array('Chuquibambilla',
                        'Curasco',
                        'Curpahuasi',
                        'Gamarra',
                        'Huayllati',
                        'Mamara',
                        'Micaela Bastidas',
                        'Pataypampa',
                        'Progreso',
                        'San Antonio',
                        'Santa Rosa',
                        'Turpay',
                        'Vilcabamba',
                        'Virundo'),
            "35"=>array("Alto Selva Alegre",
                        "Arequipa",
                        "Cayma",
                        "Cerro Colorado",
                        "Characato",
                        "Chiguata",
                        "Jacobo Hunter",
                        "José Luis Bustamante y Rivero",
                        "La Joya",
                        "Mariano Melgar",
                        "Miraflores",
                        "Mollebaya",
                        "Paucarpata",
                        "Pocsi",
                        "Polobaya",
                        "Quequeña",
                        "Sabandia",
                        "Sachaca",
                        "San Juan de Siguas",
                        "San Juan de Tarucani",
                        "Santa Isabel De Siguas",
                        "Santa Rita de Siguas",
                        "Socabaya",
                        "Tiabaya",
                        "Uchumayo",
                        "Vitor",
                        "Yanahuara",
                        "Yarabamba",
                        "Yura"),
            "36"=>array('Camaná',
                        'José MAría Quimper',
                        'Mariano Nicolas Valcarcel',
                        'Mariscal Cáceres',
                        'Nicolás de Pierola',
                        'Ocoña',
                        'Quilca',
                        'Samuel Pastor'),
            "37"=>array('Acarí',
                        'Atico',
                        'Atiquipa',
                        'Bella Unión',
                        'Cahuacho',
                        'Caraveli',
                        'Chala',
                        'Chaparra',
                        'Huanuhuanu',
                        'Jaqui',
                        'Lomas',
                        'Quicacha',
                        'Yauca'),
            "38"=>array('Andagua',
                        'Aplao',
                        'Ayo',
                        'Chachas',
                        'Chilcaymarca',
                        'Choco',
                        'Huancarqui',
                        'Machaguay',
                        'Orcopampa',
                        'Pampacolca',
                        'Tipan',
                        'Uñon',
                        'Uraca',
                        'Viraco'),
            "39"=>array('Achoma',
                        'Cabanaconde',
                        'Callalli',
                        'Caylloma',
                        'Chivay',
                        'Coporaque',
                        'Huambo',
                        'Huanca',
                        'Ichupampa',
                        'Lari',
                        'Lluta',
                        'Maca',
                        'Madrigal',
                        'Majes',
                        'San Antonio De Chuca',
                        'Sibayo',
                        'Tapay',
                        'Tisco',
                        'Tuti',
                        'Yanque'),
            "40"=>array('Andaray',
                        'Cayarani',
                        'Chichas',
                        'Chuqibamba',
                        'Iray',
                        'Rio Grande',
                        'Salamanca',
                        'Yanquihua'),
            "41"=>array('Cocachacra',
                        'Dean Valdivia',
                        'Islay',
                        'Mejia',
                        'Mollendo',
                        'Punta de Bombon'),
            "42"=>array('Alca',
                        'Charcana',
                        'Cotahuasi',
                        'Huaynacotas',
                        'Pampamarca',
                        'Puyca',
                        'Quechualla',
                        'Sayla',
                        'Tauria',
                        'Tomepampa',
                        'Toro'),
            "43"=>array('Cangallo',
                        'Chuschi',
                        'Los Morochucos',
                        'María Parado de Bellido',
                        'Paras',
                        'Totos'),
            "44"=>array('Ayahuanco',
                        'Canayre',
                        'Huamanguilla',
                        'Huanta',
                        'Iguain',
                        'Llochegua',
                        'Luricocha',
                        'Santillana',
                        'Sivia'),
            "45"=>array('Carapo',
                        'Sacasamarca',
                        'Sancos',
                        'Santiago de Lucanamarca'),
            "46"=>array('Acocro',
                        'Acos Vinchos',
                        'Ayacucho',
                        'Carmen Alto',
                        'Chiara',
                        'Jesús Nazareno',
                        'Ocros',
                        'Pacaycasa',
                        'Quinua',
                        'San José de Ticllas',
                        'San Juan Bautista',
                        'Santiago de Pischa',
                        'Socos',
                        'Tambillo',
                        'Vinchos'),
            "47"=>array('Anchihuay',
                        'Anco',
                        'Ayna',
                        'Chilcas',
                        'Chungui',
                        'Luis Carranza',
                        'Samugari',
                        'San Miguel',
                        'Santa Rosa',
                        'Tambo'),
            "48"=>array('Aucara',
                        'Cabana',
                        'Carmen Salcedo',
                        'Chaviña',
                        'Chipao',
                        'Huac-huas',
                        'Laramate',
                        'Leoncio Prado',
                        'Llauta',
                        'Lucanas',
                        'Ocaña',
                        'Otoca',
                        'Puquio',
                        'Saisa',
                        'San Cristóbal',
                        'San Juan',
                        'San Pedro',
                        'San Pedro de Palco',
                        'Sancos',
                        'Santa Ana de Huaycahuacho',
                        'Santa Lucia'),
            "49"=>array('Chumpi',
                        'Coracora',
                        'Coronel Castañeda',
                        'Pacapausa',
                        'Pullo',
                        'Puyusca',
                        'San Francisco de Ravacayco',
                        'Upahuacho'),
            "50"=>array('Colta',
                        'Corculla',
                        'Lampa',
                        'Marcabamba',
                        'Oyolo',
                        'Pararca',
                        'Pausa',
                        'San Javier de Alpabamba',
                        'San José de Ushua',
                        'Sara Sara'),
            "51"=>array('Belén',
                        'Chalcos',
                        'Chilcayoc',
                        'Huacaña',
                        'Morcolla',
                        'Paico',
                        'Querobamba',
                        'San Pedro de Larcay',
                        'San Salvador de Quije',
                        'Santiago de Paucaray',
                        'Soras'),
            "52"=>array('Alcamenca',
                        'Apongo',
                        'Asquipata',
                        'Canaria',
                        'Cayara',
                        'Colca',
                        'Huamanquiquia',
                        'Huancapi',
                        'Huancaraylla',
                        'Hualla',
                        'Sarhua',
                        'Vilcanchos'),
            "53"=>array('Accomarca',
                        'Carhuanca',
                        'Concepción',
                        'Huambalpa',
                        'Independencia',
                        'Saurama',
                        'Vilcashuamán',
                        'Vischongo'),
            "54"=>array('Cachachi',
                        'Cajabamba',
                        'Condebamba',
                        'Sitacocha'),
            "55"=>array('Asunción',
                        'Cajamarca',
                        'Chetilla',
                        'Cospan',
                        'Encañada',
                        'Jesús',
                        'Llacanora',
                        'Los Baños del Inca',
                        'Magdalena',
                        'Matara',
                        'Namora',
                        'San Juan'),
            "56"=>array('Celendín',
                        'Chumuch',
                        'Cortegana',
                        'Huasmin',
                        'Jorge Chavez',
                        'José Gálvez',
                        'La Libertad de Pallán',
                        'Miguel Iglesias',
                        'Oxamarca',
                        'Sorochuco',
                        'Sucre',
                        'Utco'),
            "57"=>array('Anguia',
                        'Chadin',
                        'Chalamarca',
                        'Chiguirip',
                        'Chimban',
                        'Choropampa',
                        'Chota',
                        'Cochabamba',
                        'Conchan',
                        'Huambos',
                        'Lajas',
                        'Llama',
                        'Miracosta',
                        'Paccha',
                        'Pion',
                        'Querocoto',
                        'San Juan de Licupis',
                        'Tacabamba',
                        'Tocmoche'),
            "58"=>array('Chilete',
                        'Contumazá',
                        'Cupisnique',
                        'Guzmango',
                        'San Benito',
                        'Santa Cruz de Toled',
                        'Tantarica',
                        'Yonan'),
            "59"=>array('Callayuc',
                        'Choros',
                        'Cujillo',
                        'Cutervo',
                        'La Ramada',
                        'Pimpingos',
                        'Querocotillo',
                        'San Andrés de Cutervo',
                        'San Juan de Cutervo',
                        'San Luis de Lucma',
                        'Santa Cruz',
                        'Santo Domingo de La Capilla',
                        'Santo Tomás',
                        'Socota',
                        'Toribio Casanova'),
            "60"=>array('Bambamarca',
                        'Chugur',
                        'Hualgayoc'),
            "61"=>array('Bellavista',
                        'Chontalí',
                        'Colasay',
                        'Huabal',
                        'Jaén',
                        'Las Pirias',
                        'Pomahuaca',
                        'Pucará',
                        'Sallique',
                        'San Felipe',
                        'San José del Alto',
                        'Santa Rosa'),
            "62"=>array('Chirinos',
                        'Huarango',
                        'La Coipa',
                        'Namballe',
                        'San Ignacio',
                        'San José de Lourdes',
                        'Tabaconas'),
            "63"=>array('Chancay',
                        'Eduardo Villanueva',
                        'Gregorio Pita',
                        'Ichocán',
                        'José Manuel Quiroz',
                        'José Sabogal',
                        'Pedro Gálvez'),
            "64"=>array('Bólivar',
                        'Calquis',
                        'Catilluc',
                        'El Prado',
                        'La Florida',
                        'Llapa',
                        'Nanchoc',
                        'Niepos',
                        'San Gregorio',
                        'San Miguel',
                        'San Silvestre de Cochán',
                        'Tongod',
                        'Unión Agua Blanca'),
            "65"=>array('San Bernardino',
                        'San Luis',
                        'San Pablo',
                        'Tumbaden'),
            "66"=>array('Andabamba',
                        'Catache',
                        'Chancaybaños',
                        'La Esperanza',
                        'Ninabamba',
                        'Pulán',
                        'Santa Cruz',
                        'Saucepampa',
                        'Sexi',
                        'Uticyacu',
                        'Yauyucan'),
            "67"=>array('Bellavista',
                        'Callao',
                        'Carmen de la Legua Reynoso',
                        'La Perla',
                        'La Puna',
                        'Mi Perú',
                        'Ventanilla'),
            "68"=>array('Acomayo',
                        'Acopia',
                        'Acos',
                        'Mosoc Llacta',
                        'Pomacanchi',
                        'Rondocan',
                        'Sangarara'),
            "69"=>array('Ancahuasi',
                        'Anta',
                        'Cachimayo',
                        'Huarocondo',
                        'Limatambo',
                        'Mollepata',
                        'Pucyura',
                        'Zurite'),
            "70"=>array('Calca',
                        'Coya',
                        'Lamay',
                        'Lares',
                        'Pisac',
                        'San Salvador',
                        'Taray',
                        'Yanatile'),
            "71"=>array('Checca',
                        'Kunturkanki',
                        'Langui',
                        'Layo',
                        'Pampamarca',
                        'Quehue',
                        'Tupac Amaru',
                        'Yanaoca'),
            "72"=>array('Checacupe',
                        'Combapata',
                        'Marangani',
                        'Pitumarca',
                        'San Pablo',
                        'San Pedro',
                        'Sicuani',
                        'Tinta'),
            "73"=>array('Echarati',
                        'Huayopata',
                        'Maranura',
                        'Ocobamba',
                        'Pichari',
                        'Quellouno',
                        'Santa Ana',
                        'Santa Teresa',
                        'Vilcabamba'),
            "74"=>array('Ccorca',
                        'Cusco',
                        'Poroy',
                        'San Jeronimo',
                        'San Sebastian',
                        'Santiago',
                        'Saylla',
                        'Wanchaq'),
            "75"=>array('Capacmarca',
                        'Chamaca',
                        'Colquemarca',
                        'Livitaca',
                        'Llusco',
                        'Quiñota',
                        'Santa Tomas',
                        'Velille'),
            "76"=>array('Alto Pichigua',
                        'Condoroma',
                        'Coporaque',
                        'Espinar',
                        'Ocoruro',
                        'Pallpata',
                        'Pichigua',
                        'Suyckutambo'),
            "77"=>array('Accha',
                        'Ccapi',
                        'Colcha',
                        'Huanoquite',
                        'Omacha',
                        'Paccaritambo',
                        'Paruro',
                        'Pillpinto',
                        'Yaurisque'),
            "78"=>array('Caicay',
                        'Challabamba',
                        'Colquepata',
                        'Huancarani',
                        'Kosñipata',
                        'Paucartambo'),
            "79"=>array('Andahuaylillas',
                        'Camanti',
                        'Ccarhuayo',
                        'Ccatca',
                        'Cusipata',
                        'Huaro',
                        'Lucre',
                        'Marcapata',
                        'Ocongate',
                        'Oropesa',
                        'Quiquijana',
                        'Urcos'),
            "80"=>array('Chinchero',
                        'Huayllabamba',
                        'Machupicchu',
                        'Maras',
                        'Ollantaytambo',
                        'Urubamba',
                        'Yucay'),
            "81"=>array('Acobamba',
                        'Andabamba',
                        'Anta',
                        'Caja',
                        'Marcas',
                        'Paucará',
                        'Pomacocha',
                        'Rosario'),
            "82"=>array('Anchonga',
                        'Callanmarca',
                        'Ccochaccasa',
                        'Chincho',
                        'Congalla',
                        'Huanca-Huanca',
                        'Huayllay Grande',
                        'Julcamarca',
                        'Lircay',
                        'San Antonio de Antaparco',
                        'Santo Tomas de Pata',
                        'Secclla'),
            "83"=>array('Arma',
                        'Aurahuá',
                        'Capillas',
                        'Castrovirreyna',
                        'Chupamarca',
                        'Cocas',
                        'Huachos',
                        'Huamatambo',
                        'Mollepampa',
                        'San Juan',
                        'Santa Ana',
                        'Tantara',
                        'Ticrapo'),
            "84"=>array('Anco',
                        'Chinchihuasi',
                        'Churcampa',
                        'El Carmen',
                        'La Merced',
                        'Locroja',
                        'Pachamarca',
                        'Pucarbamba',
                        'San Miguel de Mayocc',
                        'San Pedro de Coris'),
            "85"=>array('Acobambilla',
                        'Acoria',
                        'Ascension',
                        'Conayca',
                        'Cuenca',
                        'Hauchocolpa',
                        'Huancavelica',
                        'Huando',
                        'Huayllahuara',
                        'Izcuchaca',
                        'Laria',
                        'Manta',
                        'Mariscal Cáceres',
                        'Moya',
                        'Nuevo Occoro',
                        'Palca',
                        'Pilchaca',
                        'Vilca',
                        'Yauli'),
            "86"=>array('Ayavi',
                        'Cordova',
                        'Huayacundo Arma',
                        'Huaytara',
                        'Laramarca',
                        'Ocoyo',
                        'Pilpichaca',
                        'Querco',
                        'Quito-Arma',
                        'San Antonio de Cusicanha',
                        'San Francisco de Sangayaico',
                        'San Isidro',
                        'Santiago de Chocorvos',
                        'Santiago de Quirahuara',
                        'Santo Domingo de Capillas',
                        'Tambo'),
            "87"=>array('Acostambo',
                        'Acraquia',
                        'Ahuaycha',
                        'Colcabamba',
                        'Daniel Hernández',
                        'Huachocolpa',
                        'Huaribamba',
                        'Ñahuimpuquio',
                        'Pampas',
                        'Pazos',
                        'Quishuar',
                        'Salcabamba',
                        'Salcahuasi',
                        'San Marcos de Rocchac',
                        'Surcubamba',
                        'Tintay Puncu'),
            "88"=>array('Amarilis',
                        'Chinchao',
                        'Churubamba',
                        'Huanuco',
                        'Margos',
                        'Pillco Marca',
                        'Quisqui',
                        'San Francisco de Cayran',
                        'San Pedro de Chaulan',
                        'Santa María del Valle',
                        'Yarumayo'),
            "89"=>array('Ambo',
                        'Cayna',
                        'Colpas',
                        'Conchamarca',
                        'Huacar',
                        'San Francisco',
                        'San Rafael',
                        'Tomay Kichwa'),
            "90"=>array('Chuquis',
                        'La Unión',
                        'Marías',
                        'Pachas',
                        'Quivilla',
                        'Ripan',
                        'Shunqui',
                        'Sillapata',
                        'Yanas'),
            "91"=>array('Canchabamba',
                        'Cochabamba',
                        'Huacaybamba',
                        'Pinra'),
            "92"=>array('Arancay',
                        'Chavín de Pariarca',
                        'Jacas Grande',
                        'Jircan',
                        'Llata',
                        'Miraflores',
                        'Monzon',
                        'Punchao',
                        'Puños',
                        'Singa',
                        'Tantamayo'),
            "93"=>array('Daniel Alomias Robles',
                        'Hermilio Valdizan',
                        'José Crespo y Castillo',
                        'Luyando',
                        'Mariano Damaso Beraun',
                        'Rupa-Rupa'),
            "94"=>array('Cholon',
                        'Huacrachuco',
                        'San Buenaventura'),
            "95"=>array('Chaglla',
                        'Molino',
                        'Panao',
                        'Umari'),
            "96"=>array('Codo del Pozuzo',
                        'Honoria',
                        'Puerto Inca',
                        'Tournavista',
                        'Yuyapichis'),
            "97"=>array('Baños',
                        'Jesus',
                        'Jivia',
                        'Queropalca',
                        'Rondos',
                        'San Francisco de Asis',
                        'San Miguel de Cauri'),
            "98"=>array('Aparicio Pomares',
                        'Cachuac',
                        'Chacabamba',
                        'Chavinillo',
                        'Choras',
                        'Jacas Chico',
                        'Obas',
                        'Pampamarca'),
            "99"=>array('Alto Laran',
                        'Chavin',
                        'Chinca Alta',
                        'Chinca Baja',
                        'El Carmen',
                        'Grocio Prado',
                        'Pueblo Nuevo',
                        'San Juan de Yanac',
                        'San Pedro de Huacarpana',
                        'Sunampe',
                        'Tambo de Mora'),
            "100"=>array('Ica',
                        'La Tinguiña',
                        'Los Aquijes',
                        'Ocucaje',
                        'Pachacutec',
                        'Parcona',
                        'Pueblo Nuevo',
                        'Salas',
                        'San José de Los Molinos',
                        'San Juan Bautista',
                        'Santiago',
                        'Subtanjalla',
                        'Tate',
                        'Yauca del Rosario'),
            "101"=>array('Changuillo',
                        'El Ingenio',
                        'Marcona',
                        'Nazca',
                        'Vista Alegre'),
            "102"=>array('Llipata',
                        'Palpa',
                        'Rio Grande',
                        'Santa Cruz',
                        'Tibillo'),
            "103"=>array('Huancano',
                        'Humay',
                        'Independencia',
                        'Paracas',
                        'Pisco',
                        'San Andres',
                        'San Clemente',
                        'Tupac Amaru Inca'),
            "104"=>array('Chanchamayo',
                        'Perené',
                        'Pichanaqui',
                        'San Luis de Shuaro',
                        'San Ramón',
                        'Vitoc'),
            "105"=>array('Ahuac',
                        'Chongos Bajo',
                        'Chupaca',
                        'Huáchac',
                        'Huamancaca Chico',
                        'San Juan de Jarpa',
                        'San Juan de Yscos',
                        'Tres de Diciembre',
                        'Yanacancha'),
            "106"=>array('Aco',
                        'Andamarca',
                        'Chambara',
                        'Cochas',
                        'Comas',
                        'Concepción',
                        'Heroínas Toledo',
                        'Manzanares',
                        'Mariscal Castilla',
                        'Matahuasi',
                        'Mito',
                        'Nueve de Julio',
                        'Orcotuna',
                        'San José de Quero',
                        'Santa Rosa de Ocopa'),
            "107"=>array('Carhuacallanga',
                        'Chacapampa',
                        'Chicche',
                        'Chilca',
                        'Chongos Alto',
                        'Chupuro',
                        'Colca',
                        'Cullhuas',
                        'El Tambo',
                        'Huacrapuquio',
                        'Hualhuas',
                        'Huancan',
                        'Huancayo',
                        'Huasicancha',
                        'Huayucachi',
                        'Ingenio',
                        'Parihuanca',
                        'Pilcomayo',
                        'Pucara',
                        'Quichuay',
                        'Quilcas',
                        'San Agustín',
                        'San Jerónimo de Tunán',
                        'Saño',
                        'Santo Domingo de Acobamba',
                        'Sapallanga',
                        'Sicaya',
                        'Viques'),
            "108"=>array('Acolla',
                        'Apata',
                        'Ataura',
                        'Canchayllo',
                        'Curicaca',
                        'El Mantaro',
                        'Huamali',
                        'Huaripampa',
                        'Huertas',
                        'Janjaillo',
                        'Jauja',
                        'Julcan',
                        'Leonor Ordoñez',
                        'Llocllapampa',
                        'Marco',
                        'Masma',
                        'Masma Chicche',
                        'Molinos',
                        'Monobamba',
                        'Muqui',
                        'Muquiyauyo',
                        'Paca',
                        'Paccha',
                        'Pancan',
                        'Parco',
                        'Pomacancha',
                        'Ricran',
                        'San Lorenzo',
                        'San Pedro de Chunan',
                        'Sausa',
                        'Sincos',
                        'Tuanan Marca',
                        'Yauli',
                        'Yauyos'),
            "109"=>array('Carhuamayo',
                        'Junín',
                        'Ondores',
                        'Ulcumayo'),
            "110"=>array('Coviriali',
                        'Llaylla',
                        'Mazamari',
                        'Pampa Hermosa',
                        'Pangoa',
                        'Río Negro',
                        'Río Tambo',
                        'Satipo'),
            "111"=>array('Acobamba',
                        'Huaricolca',
                        'Huasahuasi',
                        'La Union',
                        'Palca',
                        'Palcamayo',
                        'San Pedro de Cajas',
                        'Tapo',
                        'Tarma'),
            "112"=>array('Chacapalpa',
                        'Huay-Huay',
                        'La Oroya',
                        'Marcapomacocha',
                        'Morococha',
                        'Paccha',
                        'Santa Barbara de Carhuacayan',
                        'Santa Rosa de Sacco',
                        'Suitucancha',
                        'Yauli'),


            "113"=>array('Ascope',
                          'Casa Grande',
                          'Chicama',
                          'Chocope',
                          'Magdalena de Cao',
                          'Paiján',
                          'Rázuri',
                          'Santiago de Cao'),

            "114"=>array('Bambamarca',
                          'Bolívar',
                          'Condomarca',
                          'Longotea',
                          'Uchumarca',
                          'Ucuncha'),

            "115"=>array('Chepén',
                          'Pacanga',
                          'Pueblo Nuevo'),

            "116"=>array('Cascas',
                          'Lucma',
                          'Marmot',
                          'Sayapullo'),

            "117"=>array('Calamarca',
                         'Carabamba',
                         'Huaso',
                         'Julcán'),

           "118"=>array('Agallpampa',
                        'Charat',
                        'Huaranchal',
                        'La Cuesta',
                        'Mache',
                        'Otuzco',
                        'Paranday',
                        'Salpo',
                        'Sinsicap',
                        'Usquil'),

          "119"=>array('Guadalupe',
            'Jequetepeque',
            'Pacasmayo',
            'San Jose',
            'San Pedro de LLoc'),

          "120"=>array('Buldibuyo',
                        'Chillia',
                        'Huancaspata',
                        'Huaylillas',
                        'Huayo',
                        'Ongón',
                        'Parcoy',
                        'Pataz',
                        'Pias',
                        'Santiago de Challas',
                        'Taurija',
                        'Tayabamba',
                        'Urpay'),

          "121"=>array(    'Chugay',
                          'Cochorco',
                          'Curgos',
                          'Huamachuco',
                          'Marcabal',
                          'Sanagorán',
                          'Sarín',
                          'Sartimbamba'
          ),
          "122"=>array('Angasmarca','Cachicadán','Mollebamba','Quiruvilca','Santa Cruz de Chuca','Santiago de Chuco','Sitabamba'),
          "123"=>array('El Provenir','Florencia de Mora','Huanchaco','La esperanza','Laredo','Moche','Poroto','Salaverry','Simbal','Trujillo','Víctor Larco Herrera'),
          "124"=>array('Chao','Guadalupito','Virú'),

          "125"=>array('Cayaltí','Chiclayo','Chongoyape','Eten','Jose Leonardo Ortiz','La Victoria','Lagunas','Monsefú','Nueva Arica','Oyotún','Pátapo','Picsi','Pimentel','Pomalca','Pucalá','Puerto Eten','Reque','Santa Rosa','Tuman','Zaña'),
          "126"=>array('Pítipo','Ferreñafe','Incahuasi','Kañaris','Manuel Antonio Mesones Muro','Pueblo Nuevo'),
          "127"=>array('Chocope','Illimo','Jayanca','Lambayeque','Mochumí','Mórrope','Motupe','Olmos','Pacora','Salas','San José','Túcume'),

          "128"=>array('Barranca','Paramonga','Pativilca','Supe','Supe Puerto'),
          "129"=>array('Cajatambo','Copa','Gorgor','Huancapon','Manas'),
          "130"=>array('Arahuay','Canta','Huamantanga','Huaros','Lachaqui','San Buena Ventura','Santa Rosa de Quives'),
          "131"=>array('Asia','Calango','Cerro Azul','Chilica','Coayllo','Imperial','Lunahuaná','Mala','Nuevo Imperial',
        'Pacaran','Quilmaná','San Antonio','San Luis','San Vicente de Cañete','Santa Cruz de Flores','Zuñiga'),
        "132"=>array('Atavillos Alto','Atavillos Bajo','Aucallama','Chancay','Huaral','Ihuari','Lampian','Pacaraos',
      'San Miguel de Acos','Santa Cruz de Andamarca','Sumbilca','Veintisiete de Noviembre'),

"133"=>array( 'Antioquía',
              'Callahuanca',
              'Carampoma',
              'Chicla',
              'Cuenca',
            '  Huachupampa',
              'Huanza',
              'Huarochirí',
              'Lahuaytambo',
              'Langa',
              'Laraos ',
              'Mariatana',
              'Matucana',
              'Ricardo Palma',
              'San Andrés de Tupicocha',
              'San Antonio ',
              'San Bartolomé',
              'San Damián',
              'San Juan de Iris',
              'San Juan de Tantaranche',
              'San Lorenzo de Quinti',
              'San Mateo',
              'San Mateo de Otao',
              'San Pedro de Casta',
              'San Pedro de Huancayre',
              'Sangallaya',
              'Santa Cruz de Cocachacra',
              'Santa Eulalia',
              'Santiago de Anchucaya',
              'Santiago de Tuna',
              'Santo Domingo de los Olleros',
              'San Jerónimo de Surco'),

      "134"=>array('Ambar','Caleta de Carquín','Checras','Huacho','Hualmay','Huaura','Leoncio Prado'
      ,'Paccho','Santa Leonor','Santa María','Sayán','Végueta'),

      "135"=>array(
                'Ancón',
                'Ate',
                'Barranco',
                'Breña',
                'Carabayllo',
                'Chaclacayo',
                'Chorrillos',
                'Cieneguilla',
                'Comas',
                'El Agustino',
                'Independencia',
                'Jesús María',
                'La Molina',
                'La Victoria',
                'Lima',
                'Lince',
                'Los Olivos',
                'Lurigancho-Chosica',
                'Lurín',
                'Magdalena del Mar',
                'Miraflores',
                'Pachacamac',
                'Pucusana',
                'Pueblo Libre',
                'Puente Piedra',
                'Punta Hermosa',
                'Punta Negra',
                'Rímac',
                'San Bartolo',
                'San Borja',
                'San Isidro',
                'San Juan de Lurigancho',
                'San Juan de Miraflores',
                'San Luis',
                'San Martín de Porres',
                'San Miguel',
                'Santa Anita',
                'Santa María del Mar',
                'Santa Rosa',
                'Santiago de Surco',
                'Surquillo',
                'Villa El Salvador',
                'Villa María del Triunfo'
                ),

  "136"=>array( 'Oyón',
                'Andajes',
                'Caujul',
                'Cochamarca',
                'Naván',
                'Pachangara'),

  "137"=>array(
                'Alis',
                'Ayauca3​',
                'Ayavirí',
                'Azángaro',
                'Cacra',
                'Carania',
                'Catahuasi',
                'Chocos',
                'Cochas',
                'Colonia',
                'Hongos',
                'Huampara',
                'Huancaya',
                'Huangáscar',
              '  Huantán',
                'Huañec',
                'Laraos',
                'Lincha',
                'Madean',
                'Miraflores',
                'Omas',
                'Quinches',
                'Quinocay',
                'San Lorenzo de Putinza',
                'San Joaquín',
                'San Pedro de Pilas',
                'Tanta',
                'Tauripampa',
                'Tomas',
                'Tupe',
                'Viñac',
                'Vitis',
                'Yauyos'),
          "138"=>array(
                        'Balsapuerto',
                        'Jeberos',
                        'Lagunas',
                        'Santa Cruz',
                        'Teniente César López Rojas',
                        'Yurimaguas'),
          "139"=>array(
                        'Andoas',
                        'Barranca',
                        'Cahuapanas',
                        'Manseriche',
                        'Morona',
                        'Pastaza'  ),
          "140"=>array( 'Nauta',
                        'Parinari',
                        'Tigre',
                        'Trompeteros',
                        'Urarinas'),
          "141"=>array( 'Ramón Castilla',
                        'Pebas',
                        'San Pablo',
                        'Yavarí'),

          "142"=>array(
                          'Alto Nanay',
                          'Belén​',
                          'Fernando Lores',
                          'Indiana',
                          'Iquitos',
                          'Las Amazonas',
                          'Mazán',
                          'Napo',
                          'Punchana',
                          'Putumayo',
                          'San Juan Bautista',
                          'Teniente Manuel Clavero',
                          'Torres Causana'
                        ),
          "143"=>array(
                            'Alto Tapiche',
                            'Capelo',
                            'Emilio San Martín',
                            'Maquía',
                            'Puinahua',
                            'Requena',
                            'Saquena',
                            'Soplin',
                            'Tapiche',
                            'Jenaro Herrera',
                            'Yaquerana'
                      ),
           "144"=>array(
                        'Contamana',
                        'Inahuaya',
                        'Padre Márquez',
                        'Pampa Hermosa',
                        'Alfredo Vargas Guerra'
                      ),
            "145"=>array(
                        'Fitzcarrald',
                        'Madre de Dios',
                        'Huepetuhe',
                        'Manu'
                      ),
            "146"=>array(
                        'Iberia',
                        'Iñapari',
                        'Tahuamanu'
                      ),
            "147"=>array(
                        'Inambari',
                        'Las Piedras',
                        'Laberinto',
                        'Tambopata'
                        ),
            "148"=>array(
                          'Coalaque',
                          'Chojata',
                          'Ichuña',
                          'La Capilla',
                          'Lloque',
                          'Matalaque',
                          'Omate',
                          'Puquina',
                          'Quinistaquillas',
                          'Ubinas',
                          'Yunga'
                        ),
            "149"=>array(
                      'El Algarrobal',
                      'Ilo',
                      'Pacocha'
                      ),
            "150"=>array(
                    'Carumas',
                    'Cuchumbaya',
                    'Moquegua',
                    'Samegua',
                    'San Cristóbal de Calacoa',
                    'Torata'
                    ),
            "151"=>array(
                'Chacayán',
                'Goyllarisquizga',
                'Paucar',
                'San Pedro de Pillao',
                'Santa Ana de Tusi',
                'Tápuc',
                'Vilcabamba',
                'Yanahuanca'
            ),
            "152"=>array(

                            'Chontabamba',
                            'Huancabamba',
                            'Oxapampa',
                            'Palcazu',
                            'Pozuzo',
                            'Puerto Bermúdez',
                            'Villa Rica'
            ),
            "153"=>array(
                          'Chaupimarca',
                          'Huachón',
                          'Huariaca',
                          'Huayllay',
                          'Ninacaca',
                          'Pallanchacra',
                          'Paucartambo',
                          'San Francisco de Asís de Yarusyacán',
                          'Simón Bolívar',
                          'Ticlacayán',
                          'Tinyahuarco',
                          'Vicco',
                          'Yanacancha'
            ),
            "154"=>array(
                            'Ayabaca',
                            'Frías',
                            'Jililí',
                            'Lagunas',
                            'Montero',
                            'Pacaipampa',
                            'Paimas',
                            'Sapillica',
                            'Sicchez',
                            'Suyo'
            ),
            "155"=>array(
                          'Canchaque',
                          'El Carmen de la Frontera',
                          'Huancabamba',
                          'Huarmaca',
                          'Lalaquiz',
                          'San Miguel de El Faique',
                          'Sóndor',
                          'Sondorillo'
            ),
            "156"=>array(
                        'Buenos Aires',
                        'Chalaco',
                        'Chulucanas',
                        'La Matanza',
                        'Morropón',
                        'Salitral',
                        'San Juan de Bigote',
                        'Santa Catalina de Mossa',
                        'Santo Domingo',
                        'Yamango'
            ),
            "157"=>array(

                        'Amotape',
                        'Arenal',
                        'Colán',
                        'La Huaca',
                        'Paita',
                        'Tamarindo',
                        'Vichayal'
            ),
            "158"=>array(
              'Castilla',
              'Catacaos',
              'Cura Mori',
              'El Tallán',
              'La Arena',
              'La Unión',
              'Las Lomas',
              'Piura',
              'Tambogrande'
            ),
            "159"=>array(

              'Bellavista de la Unión',
              'Bernal',
              'Cristo nos Valga',
              'Rinconada-Llicuar',
              'Sechura',
              'Vice'
            ),
            "160"=>array(

                      'Bellavista',
                      'Ignacio Escudero',
                      'Lancones',
                      'Marcavelica',
                      'Miguel Checa',
                      'Querecotillo',
                      'Salitral',
                      'Sullana'
            ),
            "161"=>array(

              'El Alto',
              'La Brea',
              'Lobitos',
              'Los Órganos',
              'Máncora',
              'Pariñas'
            ),
            "162"=>array(
                    'Achaya',
                    'Arapa',
                    'Asillo',
                    'Azángaro',
                    'Caminaca',
                    'Chupa',
                    'José Domingo Choquehuanca',
                    'Muñani',
                    'Potoni',
                    'Samán',
                    'San Antón',
                    'San José',
                    'San Juan de Salinas',
                    'Santiago de Pupuja',
                    'Tirapata'
            ),
            "163"=>array(
                    'Ajoyani',
                    'Ayapata',
                    'Coasa',
                    'Corani',
                    'Crucero',
                    'Ituata',
                    'Macusani',
                    'Ollachea',
                    'San Gabán',
                    'Usicayos'
            ),
            "164"=>array(
                    'Desaguadero',
                    'Huacullani',
                    'Juli',
                    'Kelluyo',
                    'Pisacoma',
                    'Pomata',
                    'Zepita'
            ),
            "165"=>array(
                    'Capazo',
                    'Conduriri',
                    'Ilave',
                    'Pilcuyo',
                    'Santa Rosa'
            ),
            "166"=>array(
                  'Cojota',
                  'Huancané',
                  'Huatasani',
                  'Inchupalla',
                  'Pusi',
                  'RosasPata',
                  'Taraco',
                  'Vilque Chico',
            ),
            "167"=>array(
              'Cabanilla',
              'Calapuja',
              'Lampa',
              'Nicasio',
              'Ocuviri',
              'Palca',
              'Paratía',
              'Pucará',
              'Santa Lucía',
              'Vilavila'
            ),
            "168"=>array(
                'Antauta',
                'Ayaviri',
                'Cupi',
                'Llalli',
                'Macari',
                'Ñuñoa',
                'Orurillo',
                'Santa Rosa',
                'Umachiri'
            ),
            "169"=>array(
            'Conima',
            'Huayrapata',
            'Moho',
              'Tilali'
            ),
            "170"=>array(
                'Ácora',
                'Amantaní',
                'Atuncolla',
                'Capachica',
                'Chucuito',
                'Coata',
                'Huata',
                'Mañazo',
                'Paucarcolla',
                'Pichacani',
                'Platería',
                'Puno',
                'San Antonio',
                'Tiquillaca',
                'Vilque'
            ),
            "171"=>array(
              'Ananea',
              'Pedro Vilca Apaza',
              'Putina',
              'Quilcapuncu',
              'Sina'
            ),
            "172"=>array(
              'Cabana',
              'Cabanillas',
              'Caracoto',
              'Juliaca'
            ),
            "173"=>array(
              'Alto Inambari',
              'Cuyocuyo',
              'Limbani',
              'Patambuco',
              'Phara',
              'Quiaca',
              'San Juan del Oro',
              'San Pedro de Putinapunco',
              'Sandia',
              'Yanahuaya'
            ),
            "174"=>array(
                'Yunguyo',
              	'Anapia'	,
                'Copani'	,
              	'Cuturapi',
              	'Ollaraya'	,
              	'Tinicachi'	,
                'Unicachi'
            ),
            "175"=>array(

              'Alto Biavo',
              'Bajo Biavo',
              'Bellavista',
              'Huallaga',
              'San Pablo',
              'San Rafael'
            ),
            "176"=>array(
              'San José de Sisa',
              'Agua Blanca',
              'San Martín',
              'Santa Rosa',
              'Shatoja'
            ),
            "177"=>array(

              'Alto Saposoa',
              'El Eslabón',
              'Piscoyacu',
              'Sacanche',
              'Saposoa',
              'Tingo de Saposoa'
            ),
            "178"=>array(
                'Alonso de Alvarado',
                'Barranquita',
                'Caynarachi',
                'Cuñunbuqui',
                'Lamas',
                'Pinto Recodo',
                'Rumisapa',
                'San Roque de Cumbaza',
                'Shanao',
                'Tabalosos',
                'Zapatero'
            ),
            "179"=>array(
                'Campanilla',
                'Huicungo',
                'Juanjuí',
                'Pachiza',
                'Pajarillo'
            ),
            "180"=>array(
                'Calzada',
                'Habana',
                'Jepelacio',
                'Moyobamba',
                'Soritor',
                'Yantalo'
            ),
            "181"=>array(
                'Buenos Aires',
                'Caspisapa',
                'Picota',
                'Pilluana',
                'Pucacaca',
                'San Cristobal',
                'San Hilarión',
                'Shamboyacu',
                'tingo de Ponasa',
                'Tres Unidos'
            ),
            "182"=>array(
              'Awajún'	,
              'Elias Soplin Vargas'	,
              'Nueva Cajamarca',
              'Pardo Miguel',
              'Posic',
              'Rioja',
              'San Fernando'	,
              'Yorongos'	,
              'Yuracyacu'
            ),
            "183"=>array(
                'Alberto Leveau',
                'Cacatachi',
                'Chazuta',
                'Chipurana',
                'El Porvenir',
                'Huimbayoc',
                'Juan Guerra',
                'La Banda de Shilcayo',
                'Morales',
                'Papaplaya',
                'San Antonio',
                'Sauce',
                'Shapaja',
                'Tarapoto'
            ),

            "184"=>array(
              'Tocache',
              'Nuevo Progreso',
              'Pólvora',
              'Shunte',
              'Uchiza'
            ),
            "185"=>array(

              'Cairani',
              'Camilaca',
              'Candarave',
              'Curibaya',
              'Huanuara',
              'Quilahuani'

            ),
            "186"=>array(
              'Ilabaya',
              'Ite',
              'Locumba'
            ),
            "187"=>array(
              'Alto de la Alianza',
              'Calana',
              'Ciudad Nueva',
              'Coronel Gregorio Albarracín Lanchipa',
              'Inclán',
              'Pachía',
              'Palca',
              'Pocollay',
              'Sama',
              'Tacna'
            ),
            "188"=>array(
              'Estique',
              'Estique Pampa',
              'Héroes Albarracín' ,
              'Sitajara',
              'Susapaya',
              'Tarata',
              'Tarucachi',
              'Ticaco'
            ),
            "189"=>array(

              'Casitas',
              'Zorritos'
            ),
            "190"=>array(
                'Corrales',
                'La Cruz',
                'Pampas de Hospital',
                'San Jacinto',
                'San Juan de la Virgen',
                'Tumbes'
            ),
            "191"=>array(

              'Aguas Verdes',
              'Papayal',
              'Matapalo',
              'Zarumilla'
            ),
            "192"=>array(
              'Raimondi',
	            'Sepahua',
	            'Tahuanía',
	            'Yurúa'
            ),
            "193"=>array(
              'Callería',
              'CampoVerde',
              'Iparía',
              'Manatay',
              'Masisea',
              'Nueva Requena',
              'Yarinacocha'
            ),
            "194"=>array(
              'Curimaná',
              'Irázola',
              'Padre Abad'
            ),
            "195"=>array(
              'Purús'
            )

        );
        //factory(Distrito::class,1)->create();

        foreach($distritos as $key => $value){
            foreach ($value as $nombre){
                factory(Distrito::class)->create([
                    'provincia_id'=>$key,
                    'nombre'=>$nombre
                ]);
            }
        }
    }
}
