<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Torax extends Model
{
  protected $table="toraxes";
  protected $fillable=[
'personal_tomo_placa_id',
'personal_leyo_placa_id',
'calidad',
'causa',
'numero_placa',
'fecha_placa',
'comentarios_radiografia',
'zona_afectada_superior_derecha',
'zona_afectada_superior_izquierda',
'zona_afectada_medio_derecha',
'zona_afectada_medio_izquierda',
'zona_afectada_bajo_derecha',
'zona_afectada_bajo_izquierda',
'profusion_col1_row1',
'profusion_col1_row2',
'profusion_col1_row3',
'profusion_col1_row4',
'profusion_col1_row5',
'profusion_col2_row1',
'profusion_col2_row2',
'profusion_col2_row3',
'profusion_col2_row4',
'profusion_col2_row5',
'profusion_col3_row1',
'profusion_col3_row2',
'formatamanio_primario_p',
'formatamanio_primario_q',
'formatamanio_primario_r',
'formatamanio_primario_s',
'formatamanio_primario_t',
'formatamanio_primario_u',
'formatamanio_secundario_p',
'formatamanio_secundario_q',
'formatamanio_secundario_r',
'formatamanio_secundario_s',
'formatamanio_secundario_t',
'formatamanio_secundario_u',
'opacidad_0',
'opacidad_A',
'opacidad_B',
'opacidad_C',
'anormalidad_pleural',
'sitio_pared_toraxica_0',
'sitio_pared_toraxica_D',
'sitio_pared_toraxica_I',
'sitio_defrente_0',
'sitio_defrente_D',
'sitio_defrente_I',
'sitio_diafragma_0',
'sitio_diafragma_D',
'sitio_diafragma_I',
'sitio_otros_0',
'sitio_otros_D',
'sitio_otros_I',
'clasificacion_pared_toraxica_0',
'clasificacion_pared_toraxica_D',
'clasificacion_pared_toraxica_I',
'clasificacion_defrente_0',
'clasificacion_defrente_D',
'clasificacion_defrente_I',
'clasificacion_diafragma_0',
'clasificacion_diafragma_D',
'clasificacion_diafragma_I',
'clasificacion_otros_0',
'clasificacion_otros_D',
'clasificacion_otros_I',
'extencion_col1_row1',
'extencion_col3_row1',
'extencion_col1_row2',
'extencion_col2_row2',
'extencion_col3_row2',
'extencion_col4_row1',
'extencion_col6_row1',
'extencion_col4_row2',
'extencion_col5_row2',
'extencion_col6_row2',
'ancho_col1_row1',
'ancho_col1_row2',
'ancho_col2_row2',
'ancho_col3_row2',
'ancho_col2_row1',
'ancho_col4_row2',
'ancho_col5_row2',
'ancho_col6_row2',
'angulo_costofrenico_0',
'angulo_costofrenico_D',
'angulo_costofrenico_I',
'pared_toraxica_perfil_0',
'pared_toraxica_perfil_D',
'pared_toraxica_perfil_I',
'pared_toraxica_frente_0',
'pared_toraxica_frente_D',
'pared_toraxica_frente_I',
'clasificacion_perfil_0',
'clasificacion_perfil_D',
'clasificacion_perfil_I',
'clasificacion_frente_0',
'clasificacion_frente_D',
'clasificacion_frente_I',
'extencion2_col1_row1',
'extencion2_col3_row1',
'extencion2_col1_row2',
'extencion2_col2_row2',
'extencion2_col3_row2',
'extencion2_col4_row1',
'extencion2_col6_row1',
'extencion2_col4_row2',
'extencion2_col5_row2',
'extencion2_col6_row2',
'ancho2_col1_row1',
'ancho2_col1_row2',
'ancho2_col2_row2',
'ancho2_col3_row2',
'ancho2_col2_row1',
'ancho2_col4_row2',
'ancho2_col5_row2',
'ancho2_col6_row2',
'simbolo_estado',
'simbolo_col1_row1',
'simbolo_col1_row2',
'simbolo_col1_row3',
'simbolo_col1_row4',
'simbolo_col1_row5',
'simbolo_col1_row6',
'simbolo_col1_row7',
'simbolo_col1_row8',
'simbolo_col1_row9',
'simbolo_col1_row10',
'simbolo_col1_row11',
'simbolo_col1_row12',
'simbolo_col1_row13',
'simbolo_col1_row14',
'simbolo_col1_row15',
'simbolo_col2_row1',
'simbolo_col2_row2',
'simbolo_col2_row3',
'simbolo_col2_row4',
'simbolo_col2_row5',
'simbolo_col2_row6',
'simbolo_col2_row7',
'simbolo_col2_row8',
'simbolo_col2_row9',
'simbolo_col2_row10',
'simbolo_col2_row11',
'simbolo_col2_row12',
'simbolo_col2_row13',
'simbolo_col2_row14',
'torax_conclusion',
'vertices',
'campos_pulmonares',
'hilos',
'senos',
'mediastinos',
'siluete_cardiaca',
'diafragma',
'kb',
'tiempo',
'amperaje',
'diametro_torax',
'fecha_registro',
'lista_examen_id',
'cita_id',
'estado',
'user_id'
];

public $timestamps = false;

public function cita(){
    return $this->belongsTo(Cita::class);
}

public function listaExamen(){
    return $this->belongsTo(ListaExamen::class);
}
public function personalLeyoPlaca(){
    return $this->belongsTo(Personal::class,'personal_leyo_placa_id');
}
public function personalTomoPlaca(){
    return $this->belongsTo(Personal::class,'personal_tomo_placa_id');
}
}
