<?php

namespace App\Http\Controllers;

use App\Torax;
use Illuminate\Http\Request;
use Carbon\Carbon;
use View;
use App\Cita;
use Illuminate\Support\Facades\Auth;

class ToraxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      if(request()->ajax())
      {
          $data = request()->validate([
              'personal_tomo_placa_id'=>'nullable',
              'personal_leyo_placa_id'=>'nullable',
              'calidad'=>'nullable',
              'causa'=>'nullable',
              'numero_placa'=>'nullable',
              'fecha_placa'=>'nullable',
              'comentarios_radiografia'=>'nullable',
              'zona_afectada_superior_derecha'=>'nullable',
              'zona_afectada_superior_izquierda'=>'nullable',
              'zona_afectada_medio_derecha'=>'nullable',
              'zona_afectada_medio_izquierda'=>'nullable',
              'zona_afectada_bajo_derecha'=>'nullable',
              'zona_afectada_bajo_izquierda'=>'nullable',
              'profusion_col1_row1'=>'nullable',
              'profusion_col1_row2'=>'nullable',
              'profusion_col1_row3'=>'nullable',
              'profusion_col1_row4'=>'nullable',
              'profusion_col1_row5'=>'nullable',
              'profusion_col2_row1'=>'nullable',
              'profusion_col2_row2'=>'nullable',
              'profusion_col2_row3'=>'nullable',
              'profusion_col2_row4'=>'nullable',
              'profusion_col2_row5'=>'nullable',
              'profusion_col3_row1'=>'nullable',
              'profusion_col3_row2'=>'nullable',
              'formatamanio_primario_p'=>'nullable',
              'formatamanio_primario_q'=>'nullable',
              'formatamanio_primario_r'=>'nullable',
              'formatamanio_primario_s'=>'nullable',
              'formatamanio_primario_t'=>'nullable',
              'formatamanio_primario_u'=>'nullable',
              'formatamanio_secundario_p'=>'nullable',
              'formatamanio_secundario_q'=>'nullable',
              'formatamanio_secundario_r'=>'nullable',
              'formatamanio_secundario_s'=>'nullable',
              'formatamanio_secundario_t'=>'nullable',
              'formatamanio_secundario_u'=>'nullable',
              'opacidad_0'=>'nullable',
              'opacidad_A'=>'nullable',
              'opacidad_B'=>'nullable',
              'opacidad_C'=>'nullable',
              'sitio_pared_toraxica_0'=>'nullable',
              'sitio_pared_toraxica_D'=>'nullable',
              'sitio_pared_toraxica_I'=>'nullable',
              'sitio_defrente_0'=>'nullable',
              'sitio_defrente_D'=>'nullable',
              'sitio_defrente_I'=>'nullable',
              'sitio_diafragma_0'=>'nullable',
              'sitio_diafragma_D'=>'nullable',
              'sitio_diafragma_I'=>'nullable',
              'sitio_otros_0'=>'nullable',
              'sitio_otros_D'=>'nullable',
              'sitio_otros_I'=>'nullable',
              'clasificacion_pared_toraxica_0'=>'nullable',
              'clasificacion_pared_toraxica_D'=>'nullable',
              'clasificacion_pared_toraxica_I'=>'nullable',
              'clasificacion_defrente_0'=>'nullable',
              'clasificacion_defrente_D'=>'nullable',
              'clasificacion_defrente_I'=>'nullable',
              'clasificacion_diafragma_0'=>'nullable',
              'clasificacion_diafragma_D'=>'nullable',
              'clasificacion_diafragma_I'=>'nullable',
              'clasificacion_otros_0'=>'nullable',
              'clasificacion_otros_D'=>'nullable',
              'clasificacion_otros_I'=>'nullable',
              'extencion_col1_row1'=>'nullable',
              'extencion_col3_row1'=>'nullable',
              'extencion_col1_row2'=>'nullable',
              'extencion_col2_row2'=>'nullable',
              'extencion_col3_row2'=>'nullable',
              'extencion_col4_row1'=>'nullable',
              'extencion_col6_row1'=>'nullable',
              'extencion_col4_row2'=>'nullable',
              'extencion_col5_row2'=>'nullable',
              'extencion_col6_row2'=>'nullable',
              'ancho_col1_row1'=>'nullable',
              'ancho_col1_row2'=>'nullable',
              'ancho_col2_row2'=>'nullable',
              'ancho_col3_row2'=>'nullable',
              'ancho_col2_row1'=>'nullable',
              'ancho_col4_row2'=>'nullable',
              'ancho_col5_row2'=>'nullable',
              'ancho_col6_row2'=>'nullable',
              'angulo_costofrenico_0'=>'nullable',
              'angulo_costofrenico_D'=>'nullable',
              'angulo_costofrenico_I'=>'nullable',
              'pared_toraxica_perfil_0'=>'nullable',
              'pared_toraxica_perfil_D'=>'nullable',
              'pared_toraxica_perfil_I'=>'nullable',
              'pared_toraxica_frente_0'=>'nullable',
              'pared_toraxica_frente_D'=>'nullable',
              'pared_toraxica_frente_I'=>'nullable',
              'clasificacion_perfil_0'=>'nullable',
              'clasificacion_perfil_D'=>'nullable',
              'clasificacion_perfil_I'=>'nullable',
              'clasificacion_frente_0'=>'nullable',
              'clasificacion_frente_D'=>'nullable',
              'clasificacion_frente_I'=>'nullable',
              'extencion2_col1_row1'=>'nullable',
              'extencion2_col3_row1'=>'nullable',
              'extencion2_col1_row2'=>'nullable',
              'extencion2_col2_row2'=>'nullable',
              'extencion2_col3_row2'=>'nullable',
              'extencion2_col4_row1'=>'nullable',
              'extencion2_col6_row1'=>'nullable',
              'extencion2_col4_row2'=>'nullable',
              'extencion2_col5_row2'=>'nullable',
              'extencion2_col6_row2'=>'nullable',
              'ancho2_col1_row1'=>'nullable',
              'ancho2_col1_row2'=>'nullable',
              'ancho2_col2_row2'=>'nullable',
              'ancho2_col3_row2'=>'nullable',
              'ancho2_col2_row1'=>'nullable',
              'ancho2_col4_row2'=>'nullable',
              'ancho2_col5_row2'=>'nullable',
              'ancho2_col6_row2'=>'nullable',
              'simbolo_estado'=>'nullable',
              'simbolo_col1_row1'=>'nullable',
              'simbolo_col1_row2'=>'nullable',
              'simbolo_col1_row3'=>'nullable',
              'simbolo_col1_row4'=>'nullable',
              'simbolo_col1_row5'=>'nullable',
              'simbolo_col1_row6'=>'nullable',
              'simbolo_col1_row7'=>'nullable',
              'simbolo_col1_row8'=>'nullable',
              'simbolo_col1_row9'=>'nullable',
              'simbolo_col1_row10'=>'nullable',
              'simbolo_col1_row11'=>'nullable',
              'simbolo_col1_row12'=>'nullable',
              'simbolo_col1_row13'=>'nullable',
              'simbolo_col1_row14'=>'nullable',
              'simbolo_col1_row15'=>'nullable',
              'simbolo_col2_row1'=>'nullable',
              'simbolo_col2_row2'=>'nullable',
              'simbolo_col2_row3'=>'nullable',
              'simbolo_col2_row4'=>'nullable',
              'simbolo_col2_row5'=>'nullable',
              'simbolo_col2_row6'=>'nullable',
              'simbolo_col2_row7'=>'nullable',
              'simbolo_col2_row8'=>'nullable',
              'simbolo_col2_row9'=>'nullable',
              'simbolo_col2_row10'=>'nullable',
              'simbolo_col2_row11'=>'nullable',
              'simbolo_col2_row12'=>'nullable',
              'simbolo_col2_row13'=>'nullable',
              'simbolo_col2_row14'=>'nullable',
              'torax_conclusion'=>'nullable',
              'vertices'=>'nullable',
              'campos_pulmonares'=>'nullable',
              'hilos'=>'nullable',
              'senos'=>'nullable',
              'mediastinos'=>'nullable',
              'siluete_cardiaca'=>'nullable',
              'diafragma'=>'nullable',
              'kb'=>'nullable',
              'tiempo'=>'nullable',
              'amperaje'=>'nullable',
              'diametro_torax'=>'nullable',
              'fecha_registro'=>'nullable',
              'lista_examen_id'=>'nullable',
              'cita_id'=>'nullable',
          ]);

          $torax = Torax::create([
            'personal_tomo_placa_id'=>isset($data['personal_tomo_placa_id'])? $data['personal_tomo_placa_id']:null,
            'personal_leyo_placa_id'=>isset($data['personal_leyo_placa_id'])? $data['personal_leyo_placa_id']:null,
            'calidad'=>isset($data['calidad'])? $data['calidad']:null,
            'causa'=>isset($data['causa'])? $data['causa']:null,
            'numero_placa'=>isset($data['numero_placa'])? $data['numero_placa']:null,
            'fecha_placa'=>isset($data['fecha_placa'])? $data['fecha_placa']:null,
            'comentarios_radiografia'=>isset($data['comentarios_radiografia'])? $data['comentarios_radiografia']:null,
            'zona_afectada_superior_derecha'=>isset($data['zona_afectada_superior_derecha'])? $data['zona_afectada_superior_derecha']:0,
            'zona_afectada_superior_izquierda'=>isset($data['zona_afectada_superior_izquierda'])? $data['zona_afectada_superior_izquierda']:0,
            'zona_afectada_medio_derecha'=>isset($data['zona_afectada_medio_derecha'])? $data['zona_afectada_medio_derecha']:0,
            'zona_afectada_medio_izquierda'=>isset($data['zona_afectada_medio_izquierda'])? $data['zona_afectada_medio_izquierda']:0,
            'zona_afectada_bajo_derecha'=>isset($data['zona_afectada_bajo_derecha'])? $data['zona_afectada_bajo_derecha']:0,
            'zona_afectada_bajo_izquierda'=>isset($data['zona_afectada_bajo_izquierda'])? $data['zona_afectada_bajo_izquierda']:0,
            'profusion_col1_row1'=>isset($data['profusion_col1_row1'])? $data['profusion_col1_row1']:0,
            'profusion_col1_row2'=>isset($data['profusion_col1_row2'])? $data['profusion_col1_row2']:0,
            'profusion_col1_row3'=>isset($data['profusion_col1_row3'])? $data['profusion_col1_row3']:0,
            'profusion_col1_row4'=>isset($data['profusion_col1_row4'])? $data['profusion_col1_row4']:0,
            'profusion_col1_row5'=>isset($data['profusion_col1_row5'])? $data['profusion_col1_row5']:0,
            'profusion_col2_row1'=>isset($data['profusion_col2_row1'])? $data['profusion_col2_row1']:0,
            'profusion_col2_row2'=>isset($data['profusion_col2_row2'])? $data['profusion_col2_row2']:0,
            'profusion_col2_row3'=>isset($data['profusion_col2_row3'])? $data['profusion_col2_row3']:0,
            'profusion_col2_row4'=>isset($data['profusion_col2_row4'])? $data['profusion_col2_row4']:0,
            'profusion_col2_row5'=>isset($data['profusion_col2_row5'])? $data['profusion_col2_row5']:0,
            'profusion_col3_row1'=>isset($data['profusion_col3_row1'])? $data['profusion_col3_row1']:0,
            'profusion_col3_row2'=>isset($data['profusion_col3_row2'])? $data['profusion_col3_row2']:0,
            'formatamanio_primario_p'=>isset($data['formatamanio_primario_p'])? $data['formatamanio_primario_p']:0,
            'formatamanio_primario_q'=>isset($data['formatamanio_primario_q'])? $data['formatamanio_primario_q']:0,
            'formatamanio_primario_r'=>isset($data['formatamanio_primario_r'])? $data['formatamanio_primario_r']:0,
            'formatamanio_primario_s'=>isset($data['formatamanio_primario_s'])? $data['formatamanio_primario_s']:0,
            'formatamanio_primario_t'=>isset($data['formatamanio_primario_t'])? $data['formatamanio_primario_t']:0,
            'formatamanio_primario_u'=>isset($data['formatamanio_primario_u'])? $data['formatamanio_primario_u']:0,
            'formatamanio_secundario_p'=>isset($data['formatamanio_secundario_p'])? $data['formatamanio_secundario_p']:0,
            'formatamanio_secundario_q'=>isset($data['formatamanio_secundario_q'])? $data['formatamanio_secundario_q']:0,
            'formatamanio_secundario_r'=>isset($data['formatamanio_secundario_r'])? $data['formatamanio_secundario_r']:0,
            'formatamanio_secundario_s'=>isset($data['formatamanio_secundario_s'])? $data['formatamanio_secundario_s']:0,
            'formatamanio_secundario_t'=>isset($data['formatamanio_secundario_t'])? $data['formatamanio_secundario_t']:0,
            'formatamanio_secundario_u'=>isset($data['formatamanio_secundario_u'])? $data['formatamanio_secundario_u']:0,
            'opacidad_0'=>isset($data['opacidad_0'])? $data['opacidad_0']:0,
            'opacidad_A'=>isset($data['opacidad_A'])? $data['opacidad_A']:0,
            'opacidad_B'=>isset($data['opacidad_B'])? $data['opacidad_B']:0,
            'opacidad_C'=>isset($data['opacidad_C'])? $data['opacidad_C']:0,
            'sitio_pared_toraxica_0'=>isset($data['sitio_pared_toraxica_0'])? $data['sitio_pared_toraxica_0']:0,
            'sitio_pared_toraxica_D'=>isset($data['sitio_pared_toraxica_D'])? $data['sitio_pared_toraxica_D']:0,
            'sitio_pared_toraxica_I'=>isset($data['sitio_pared_toraxica_I'])? $data['sitio_pared_toraxica_I']:0,
            'sitio_defrente_0'=>isset($data['sitio_defrente_0'])? $data['sitio_defrente_0']:0,
            'sitio_defrente_D'=>isset($data['sitio_defrente_D'])? $data['sitio_defrente_D']:0,
            'sitio_defrente_I'=>isset($data['sitio_defrente_I'])? $data['sitio_defrente_I']:0,
            'sitio_diafragma_0'=>isset($data['sitio_diafragma_0'])? $data['sitio_diafragma_0']:0,
            'sitio_diafragma_D'=>isset($data['sitio_diafragma_D'])? $data['sitio_diafragma_D']:0,
            'sitio_diafragma_I'=>isset($data['sitio_diafragma_I'])? $data['sitio_diafragma_I']:0,
            'sitio_otros_0'=>isset($data['sitio_otros_0'])? $data['sitio_otros_0']:0,
            'sitio_otros_D'=>isset($data['sitio_otros_D'])? $data['sitio_otros_D']:0,
            'sitio_otros_I'=>isset($data['sitio_otros_I'])? $data['sitio_otros_I']:0,
            'clasificacion_pared_toraxica_0'=>isset($data['clasificacion_pared_toraxica_0'])? $data['clasificacion_pared_toraxica_0']:0,
            'clasificacion_pared_toraxica_D'=>isset($data['clasificacion_pared_toraxica_D'])? $data['clasificacion_pared_toraxica_D']:0,
            'clasificacion_pared_toraxica_I'=>isset($data['clasificacion_pared_toraxica_I'])? $data['clasificacion_pared_toraxica_I']:0,
            'clasificacion_defrente_0'=>isset($data['clasificacion_defrente_0'])? $data['clasificacion_defrente_0']:0,
            'clasificacion_defrente_D'=>isset($data['clasificacion_defrente_D'])? $data['clasificacion_defrente_D']:0,
            'clasificacion_defrente_I'=>isset($data['clasificacion_defrente_I'])? $data['clasificacion_defrente_I']:0,
            'clasificacion_diafragma_0'=>isset($data['clasificacion_diafragma_0'])? $data['clasificacion_diafragma_0']:0,
            'clasificacion_diafragma_D'=>isset($data['clasificacion_diafragma_D'])? $data['clasificacion_diafragma_D']:0,
            'clasificacion_diafragma_I'=>isset($data['clasificacion_diafragma_I'])? $data['clasificacion_diafragma_I']:0,
            'clasificacion_otros_0'=>isset($data['clasificacion_otros_0'])? $data['clasificacion_otros_0']:0,
            'clasificacion_otros_D'=>isset($data['clasificacion_otros_D'])? $data['clasificacion_otros_D']:0,
            'clasificacion_otros_I'=>isset($data['clasificacion_otros_I'])? $data['clasificacion_otros_I']:0,
            'extencion_col1_row1'=>isset($data['extencion_col1_row1'])? $data['extencion_col1_row1']:0,
            'extencion_col3_row1'=>isset($data['extencion_col3_row1'])? $data['extencion_col3_row1']:0,
            'extencion_col1_row2'=>isset($data['extencion_col1_row2'])? $data['extencion_col1_row2']:0,
            'extencion_col2_row2'=>isset($data['extencion_col2_row2'])? $data['extencion_col2_row2']:0,
            'extencion_col3_row2'=>isset($data['extencion_col3_row2'])? $data['extencion_col3_row2']:0,
            'extencion_col4_row1'=>isset($data['extencion_col4_row1'])? $data['extencion_col4_row1']:0,
            'extencion_col6_row1'=>isset($data['extencion_col6_row1'])? $data['extencion_col6_row1']:0,
            'extencion_col4_row2'=>isset($data['extencion_col4_row2'])? $data['extencion_col4_row2']:0,
            'extencion_col5_row2'=>isset($data['extencion_col5_row2'])? $data['extencion_col5_row2']:0,
            'extencion_col6_row2'=>isset($data['extencion_col6_row2'])? $data['extencion_col6_row2']:0,
            'ancho_col1_row1'=>isset($data['ancho_col1_row1'])? $data['ancho_col1_row1']:0,
            'ancho_col1_row2'=>isset($data['ancho_col1_row2'])? $data['ancho_col1_row2']:0,
            'ancho_col2_row2'=>isset($data['ancho_col2_row2'])? $data['ancho_col2_row2']:0,
            'ancho_col3_row2'=>isset($data['ancho_col3_row2'])? $data['ancho_col3_row2']:0,
            'ancho_col2_row1'=>isset($data['ancho_col2_row1'])? $data['ancho_col2_row1']:0,
            'ancho_col4_row2'=>isset($data['ancho_col4_row2'])? $data['ancho_col4_row2']:0,
            'ancho_col5_row2'=>isset($data['ancho_col5_row2'])? $data['ancho_col5_row2']:0,
            'ancho_col6_row2'=>isset($data['ancho_col6_row2'])? $data['ancho_col6_row2']:0,
            'angulo_costofrenico_0'=>isset($data['angulo_costofrenico_0'])? $data['angulo_costofrenico_0']:0,
            'angulo_costofrenico_D'=>isset($data['angulo_costofrenico_D'])? $data['angulo_costofrenico_D']:0,
            'angulo_costofrenico_I'=>isset($data['angulo_costofrenico_I'])? $data['angulo_costofrenico_I']:0,
            'pared_toraxica_perfil_0'=>isset($data['pared_toraxica_perfil_0'])? $data['pared_toraxica_perfil_0']:0,
            'pared_toraxica_perfil_D'=>isset($data['pared_toraxica_perfil_D'])? $data['pared_toraxica_perfil_D']:0,
            'pared_toraxica_perfil_I'=>isset($data['pared_toraxica_perfil_I'])? $data['pared_toraxica_perfil_I']:0,
            'pared_toraxica_frente_0'=>isset($data['pared_toraxica_frente_0'])? $data['pared_toraxica_frente_0']:0,
            'pared_toraxica_frente_D'=>isset($data['pared_toraxica_frente_D'])? $data['pared_toraxica_frente_D']:0,
            'pared_toraxica_frente_I'=>isset($data['pared_toraxica_frente_I'])? $data['pared_toraxica_frente_I']:0,
            'clasificacion_perfil_0'=>isset($data['clasificacion_perfil_0'])? $data['clasificacion_perfil_0']:0,
            'clasificacion_perfil_D'=>isset($data['clasificacion_perfil_D'])? $data['clasificacion_perfil_D']:0,
            'clasificacion_perfil_I'=>isset($data['clasificacion_perfil_I'])? $data['clasificacion_perfil_I']:0,
            'clasificacion_frente_0'=>isset($data['clasificacion_frente_0'])? $data['clasificacion_frente_0']:0,
            'clasificacion_frente_D'=>isset($data['clasificacion_frente_D'])? $data['clasificacion_frente_D']:0,
            'clasificacion_frente_I'=>isset($data['clasificacion_frente_I'])? $data['clasificacion_frente_I']:0,
            'extencion2_col1_row1'=>isset($data['extencion2_col1_row1'])? $data['extencion2_col1_row1']:0,
            'extencion2_col3_row1'=>isset($data['extencion2_col3_row1'])? $data['extencion2_col3_row1']:0,
            'extencion2_col1_row2'=>isset($data['extencion2_col1_row2'])? $data['extencion2_col1_row2']:0,
            'extencion2_col2_row2'=>isset($data['extencion2_col2_row2'])? $data['extencion2_col2_row2']:0,
            'extencion2_col3_row2'=>isset($data['extencion2_col3_row2'])? $data['extencion2_col3_row2']:0,
            'extencion2_col4_row1'=>isset($data['extencion2_col4_row1'])? $data['extencion2_col4_row1']:0,
            'extencion2_col6_row1'=>isset($data['extencion2_col6_row1'])? $data['extencion2_col6_row1']:0,
            'extencion2_col4_row2'=>isset($data['extencion2_col4_row2'])? $data['extencion2_col4_row2']:0,
            'extencion2_col5_row2'=>isset($data['extencion2_col5_row2'])? $data['extencion2_col5_row2']:0,
            'extencion2_col6_row2'=>isset($data['extencion2_col6_row2'])? $data['extencion2_col6_row2']:0,
            'ancho2_col1_row1'=>isset($data['ancho2_col1_row1'])? $data['ancho2_col1_row1']:0,
            'ancho2_col1_row2'=>isset($data['ancho2_col1_row2'])? $data['ancho2_col1_row2']:0,
            'ancho2_col2_row2'=>isset($data['ancho2_col2_row2'])? $data['ancho2_col2_row2']:0,
            'ancho2_col3_row2'=>isset($data['ancho2_col3_row2'])? $data['ancho2_col3_row2']:0,
            'ancho2_col2_row1'=>isset($data['ancho2_col2_row1'])? $data['ancho2_col2_row1']:0,
            'ancho2_col4_row2'=>isset($data['ancho2_col4_row2'])? $data['ancho2_col4_row2']:0,
            'ancho2_col5_row2'=>isset($data['ancho2_col5_row2'])? $data['ancho2_col5_row2']:0,
            'ancho2_col6_row2'=>isset($data['ancho2_col6_row2'])? $data['ancho2_col6_row2']:0,
            'simbolo_estado'=>isset($data['simbolo_estado'])? $data['simbolo_estado']:0,
            'simbolo_col1_row1'=>isset($data['simbolo_col1_row1'])? $data['simbolo_col1_row1']:0,
            'simbolo_col1_row2'=>isset($data['simbolo_col1_row2'])? $data['simbolo_col1_row2']:0,
            'simbolo_col1_row3'=>isset($data['simbolo_col1_row3'])? $data['simbolo_col1_row3']:0,
            'simbolo_col1_row4'=>isset($data['simbolo_col1_row4'])? $data['simbolo_col1_row4']:0,
            'simbolo_col1_row5'=>isset($data['simbolo_col1_row5'])? $data['simbolo_col1_row5']:0,
            'simbolo_col1_row6'=>isset($data['simbolo_col1_row6'])? $data['simbolo_col1_row6']:0,
            'simbolo_col1_row7'=>isset($data['simbolo_col1_row7'])? $data['simbolo_col1_row7']:0,
            'simbolo_col1_row8'=>isset($data['simbolo_col1_row8'])? $data['simbolo_col1_row8']:0,
            'simbolo_col1_row9'=>isset($data['simbolo_col1_row9'])? $data['simbolo_col1_row9']:0,
            'simbolo_col1_row10'=>isset($data['simbolo_col1_row10'])? $data['simbolo_col1_row10']:0,
            'simbolo_col1_row11'=>isset($data['simbolo_col1_row11'])? $data['simbolo_col1_row11']:0,
            'simbolo_col1_row12'=>isset($data['simbolo_col1_row12'])? $data['simbolo_col1_row12']:0,
            'simbolo_col1_row13'=>isset($data['simbolo_col1_row13'])? $data['simbolo_col1_row13']:0,
            'simbolo_col1_row14'=>isset($data['simbolo_col1_row14'])? $data['simbolo_col1_row14']:0,
            'simbolo_col1_row15'=>isset($data['simbolo_col1_row15'])? $data['simbolo_col1_row15']:0,
            'simbolo_col2_row1'=>isset($data['simbolo_col2_row1'])? $data['simbolo_col2_row1']:0,
            'simbolo_col2_row2'=>isset($data['simbolo_col2_row2'])? $data['simbolo_col2_row2']:0,
            'simbolo_col2_row3'=>isset($data['simbolo_col2_row3'])? $data['simbolo_col2_row3']:0,
            'simbolo_col2_row4'=>isset($data['simbolo_col2_row4'])? $data['simbolo_col2_row4']:0,
            'simbolo_col2_row5'=>isset($data['simbolo_col2_row5'])? $data['simbolo_col2_row5']:0,
            'simbolo_col2_row6'=>isset($data['simbolo_col2_row6'])? $data['simbolo_col2_row6']:0,
            'simbolo_col2_row7'=>isset($data['simbolo_col2_row7'])? $data['simbolo_col2_row7']:0,
            'simbolo_col2_row8'=>isset($data['simbolo_col2_row8'])? $data['simbolo_col2_row8']:0,
            'simbolo_col2_row9'=>isset($data['simbolo_col2_row9'])? $data['simbolo_col2_row9']:0,
            'simbolo_col2_row10'=>isset($data['simbolo_col2_row10'])? $data['simbolo_col2_row10']:0,
            'simbolo_col2_row11'=>isset($data['simbolo_col2_row11'])? $data['simbolo_col2_row11']:0,
            'simbolo_col2_row12'=>isset($data['simbolo_col2_row12'])? $data['simbolo_col2_row12']:0,
            'simbolo_col2_row13'=>isset($data['simbolo_col2_row13'])? $data['simbolo_col2_row13']:0,
            'simbolo_col2_row14'=>isset($data['simbolo_col2_row14'])? $data['simbolo_col2_row14']:0,
            'torax_conclusion'=>isset($data['torax_conclusion'])? $data['torax_conclusion']:null,
            'vertices'=>isset($data['vertices'])? $data['vertices']:null,
            'campos_pulmonares'=>isset($data['campos_pulmonares'])? $data['campos_pulmonares']:null,
            'hilos'=>isset($data['hilos'])? $data['hilos']:null,
            'senos'=>isset($data['senos'])? $data['senos']:null,
            'mediastinos'=>isset($data['mediastinos'])? $data['mediastinos']:null,
            'siluete_cardiaca'=>isset($data['siluete_cardiaca'])? $data['siluete_cardiaca']:null,
            'diafragma'=>isset($data['diafragma'])? $data['diafragma']:null,
            'kb'=>isset($data['kb'])? $data['kb']:null,
            'tiempo'=>isset($data['tiempo'])? $data['tiempo']:null,
            'amperaje'=>isset($data['amperaje'])? $data['amperaje']:null,
            'diametro_torax'=>isset($data['diametro_torax'])? $data['diametro_torax']:null,
           'fecha_registro'=>Carbon::now(),
           'lista_examen_id'=>isset($data['lista_examen_id'])? $data['lista_examen_id']:null,
           'cita_id'=>isset($data['cita_id'])? $data['cita_id']:null,
           'estado'=>true
          ]);
          return response()->json(['mensaje' =>"registro exitoso"]);
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Torax  $torax
     * @return \Illuminate\Http\Response
     */
    public function show(Torax $torax)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Torax  $torax
     * @return \Illuminate\Http\Response
     */
    public function edit(Torax $torax)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Torax  $torax
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $torax = Torax::find($request['torax_id']);
      if(request()->ajax())
      {
          $data = request()->validate([
              'personal_tomo_placa_id'=>'nullable',
              'personal_leyo_placa_id'=>'nullable',
              'calidad'=>'nullable',
              'causa'=>'nullable',
              'numero_placa'=>'nullable',
              'fecha_placa'=>'nullable',
              'comentarios_radiografia'=>'nullable',
              'zona_afectada_superior_derecha'=>'nullable',
              'zona_afectada_superior_izquierda'=>'nullable',
              'zona_afectada_medio_derecha'=>'nullable',
              'zona_afectada_medio_izquierda'=>'nullable',
              'zona_afectada_bajo_derecha'=>'nullable',
              'zona_afectada_bajo_izquierda'=>'nullable',
              'profusion_col1_row1'=>'nullable',
              'profusion_col1_row2'=>'nullable',
              'profusion_col1_row3'=>'nullable',
              'profusion_col1_row4'=>'nullable',
              'profusion_col1_row5'=>'nullable',
              'profusion_col2_row1'=>'nullable',
              'profusion_col2_row2'=>'nullable',
              'profusion_col2_row3'=>'nullable',
              'profusion_col2_row4'=>'nullable',
              'profusion_col2_row5'=>'nullable',
              'profusion_col3_row1'=>'nullable',
              'profusion_col3_row2'=>'nullable',
              'formatamanio_primario_p'=>'nullable',
              'formatamanio_primario_q'=>'nullable',
              'formatamanio_primario_r'=>'nullable',
              'formatamanio_primario_s'=>'nullable',
              'formatamanio_primario_t'=>'nullable',
              'formatamanio_primario_u'=>'nullable',
              'formatamanio_secundario_p'=>'nullable',
              'formatamanio_secundario_q'=>'nullable',
              'formatamanio_secundario_r'=>'nullable',
              'formatamanio_secundario_s'=>'nullable',
              'formatamanio_secundario_t'=>'nullable',
              'formatamanio_secundario_u'=>'nullable',
              'opacidad_0'=>'nullable',
              'opacidad_A'=>'nullable',
              'opacidad_B'=>'nullable',
              'opacidad_C'=>'nullable',
              'sitio_pared_toraxica_0'=>'nullable',
              'sitio_pared_toraxica_D'=>'nullable',
              'sitio_pared_toraxica_I'=>'nullable',
              'sitio_defrente_0'=>'nullable',
              'sitio_defrente_D'=>'nullable',
              'sitio_defrente_I'=>'nullable',
              'sitio_diafragma_0'=>'nullable',
              'sitio_diafragma_D'=>'nullable',
              'sitio_diafragma_I'=>'nullable',
              'sitio_otros_0'=>'nullable',
              'sitio_otros_D'=>'nullable',
              'sitio_otros_I'=>'nullable',
              'clasificacion_pared_toraxica_0'=>'nullable',
              'clasificacion_pared_toraxica_D'=>'nullable',
              'clasificacion_pared_toraxica_I'=>'nullable',
              'clasificacion_defrente_0'=>'nullable',
              'clasificacion_defrente_D'=>'nullable',
              'clasificacion_defrente_I'=>'nullable',
              'clasificacion_diafragma_0'=>'nullable',
              'clasificacion_diafragma_D'=>'nullable',
              'clasificacion_diafragma_I'=>'nullable',
              'clasificacion_otros_0'=>'nullable',
              'clasificacion_otros_D'=>'nullable',
              'clasificacion_otros_I'=>'nullable',
              'extencion_col1_row1'=>'nullable',
              'extencion_col3_row1'=>'nullable',
              'extencion_col1_row2'=>'nullable',
              'extencion_col2_row2'=>'nullable',
              'extencion_col3_row2'=>'nullable',
              'extencion_col4_row1'=>'nullable',
              'extencion_col6_row1'=>'nullable',
              'extencion_col4_row2'=>'nullable',
              'extencion_col5_row2'=>'nullable',
              'extencion_col6_row2'=>'nullable',
              'ancho_col1_row1'=>'nullable',
              'ancho_col1_row2'=>'nullable',
              'ancho_col2_row2'=>'nullable',
              'ancho_col3_row2'=>'nullable',
              'ancho_col2_row1'=>'nullable',
              'ancho_col4_row2'=>'nullable',
              'ancho_col5_row2'=>'nullable',
              'ancho_col6_row2'=>'nullable',
              'angulo_costofrenico_0'=>'nullable',
              'angulo_costofrenico_D'=>'nullable',
              'angulo_costofrenico_I'=>'nullable',
              'pared_toraxica_perfil_0'=>'nullable',
              'pared_toraxica_perfil_D'=>'nullable',
              'pared_toraxica_perfil_I'=>'nullable',
              'pared_toraxica_frente_0'=>'nullable',
              'pared_toraxica_frente_D'=>'nullable',
              'pared_toraxica_frente_I'=>'nullable',
              'clasificacion_perfil_0'=>'nullable',
              'clasificacion_perfil_D'=>'nullable',
              'clasificacion_perfil_I'=>'nullable',
              'clasificacion_frente_0'=>'nullable',
              'clasificacion_frente_D'=>'nullable',
              'clasificacion_frente_I'=>'nullable',
              'extencion2_col1_row1'=>'nullable',
              'extencion2_col3_row1'=>'nullable',
              'extencion2_col1_row2'=>'nullable',
              'extencion2_col2_row2'=>'nullable',
              'extencion2_col3_row2'=>'nullable',
              'extencion2_col4_row1'=>'nullable',
              'extencion2_col6_row1'=>'nullable',
              'extencion2_col4_row2'=>'nullable',
              'extencion2_col5_row2'=>'nullable',
              'extencion2_col6_row2'=>'nullable',
              'ancho2_col1_row1'=>'nullable',
              'ancho2_col1_row2'=>'nullable',
              'ancho2_col2_row2'=>'nullable',
              'ancho2_col3_row2'=>'nullable',
              'ancho2_col2_row1'=>'nullable',
              'ancho2_col4_row2'=>'nullable',
              'ancho2_col5_row2'=>'nullable',
              'ancho2_col6_row2'=>'nullable',
              'simbolo_estado'=>'nullable',
              'simbolo_col1_row1'=>'nullable',
              'simbolo_col1_row2'=>'nullable',
              'simbolo_col1_row3'=>'nullable',
              'simbolo_col1_row4'=>'nullable',
              'simbolo_col1_row5'=>'nullable',
              'simbolo_col1_row6'=>'nullable',
              'simbolo_col1_row7'=>'nullable',
              'simbolo_col1_row8'=>'nullable',
              'simbolo_col1_row9'=>'nullable',
              'simbolo_col1_row10'=>'nullable',
              'simbolo_col1_row11'=>'nullable',
              'simbolo_col1_row12'=>'nullable',
              'simbolo_col1_row13'=>'nullable',
              'simbolo_col1_row14'=>'nullable',
              'simbolo_col1_row15'=>'nullable',
              'simbolo_col2_row1'=>'nullable',
              'simbolo_col2_row2'=>'nullable',
              'simbolo_col2_row3'=>'nullable',
              'simbolo_col2_row4'=>'nullable',
              'simbolo_col2_row5'=>'nullable',
              'simbolo_col2_row6'=>'nullable',
              'simbolo_col2_row7'=>'nullable',
              'simbolo_col2_row8'=>'nullable',
              'simbolo_col2_row9'=>'nullable',
              'simbolo_col2_row10'=>'nullable',
              'simbolo_col2_row11'=>'nullable',
              'simbolo_col2_row12'=>'nullable',
              'simbolo_col2_row13'=>'nullable',
              'simbolo_col2_row14'=>'nullable',
              'torax_conclusion'=>'nullable',
              'vertices'=>'nullable',
              'campos_pulmonares'=>'nullable',
              'hilos'=>'nullable',
              'senos'=>'nullable',
              'mediastinos'=>'nullable',
              'siluete_cardiaca'=>'nullable',
              'diafragma'=>'nullable',
              'kb'=>'nullable',
              'tiempo'=>'nullable',
              'amperaje'=>'nullable',
              'diametro_torax'=>'nullable',
              'fecha_registro'=>'nullable',
              'lista_examen_id'=>'nullable',
              'cita_id'=>'nullable',
          ]);

          $torax->update([
            'personal_tomo_placa_id'=>isset($data['personal_tomo_placa_id'])? $data['personal_tomo_placa_id']:null,
            'personal_leyo_placa_id'=>isset($data['personal_leyo_placa_id'])? $data['personal_leyo_placa_id']:null,
            'calidad'=>isset($data['calidad'])? $data['calidad']:null,
            'causa'=>isset($data['causa'])? $data['causa']:null,
            'numero_placa'=>isset($data['numero_placa'])? $data['numero_placa']:null,
            'fecha_placa'=>isset($data['fecha_placa'])? $data['fecha_placa']:null,
            'comentarios_radiografia'=>isset($data['comentarios_radiografia'])? $data['comentarios_radiografia']:null,
            'zona_afectada_superior_derecha'=>isset($data['zona_afectada_superior_derecha'])? $data['zona_afectada_superior_derecha']:0,
            'zona_afectada_superior_izquierda'=>isset($data['zona_afectada_superior_izquierda'])? $data['zona_afectada_superior_izquierda']:0,
            'zona_afectada_medio_derecha'=>isset($data['zona_afectada_medio_derecha'])? $data['zona_afectada_medio_derecha']:0,
            'zona_afectada_medio_izquierda'=>isset($data['zona_afectada_medio_izquierda'])? $data['zona_afectada_medio_izquierda']:0,
            'zona_afectada_bajo_derecha'=>isset($data['zona_afectada_bajo_derecha'])? $data['zona_afectada_bajo_derecha']:0,
            'zona_afectada_bajo_izquierda'=>isset($data['zona_afectada_bajo_izquierda'])? $data['zona_afectada_bajo_izquierda']:0,
            'profusion_col1_row1'=>isset($data['profusion_col1_row1'])? $data['profusion_col1_row1']:0,
            'profusion_col1_row2'=>isset($data['profusion_col1_row2'])? $data['profusion_col1_row2']:0,
            'profusion_col1_row3'=>isset($data['profusion_col1_row3'])? $data['profusion_col1_row3']:0,
            'profusion_col1_row4'=>isset($data['profusion_col1_row4'])? $data['profusion_col1_row4']:0,
            'profusion_col1_row5'=>isset($data['profusion_col1_row5'])? $data['profusion_col1_row5']:0,
            'profusion_col2_row1'=>isset($data['profusion_col2_row1'])? $data['profusion_col2_row1']:0,
            'profusion_col2_row2'=>isset($data['profusion_col2_row2'])? $data['profusion_col2_row2']:0,
            'profusion_col2_row3'=>isset($data['profusion_col2_row3'])? $data['profusion_col2_row3']:0,
            'profusion_col2_row4'=>isset($data['profusion_col2_row4'])? $data['profusion_col2_row4']:0,
            'profusion_col2_row5'=>isset($data['profusion_col2_row5'])? $data['profusion_col2_row5']:0,
            'profusion_col3_row1'=>isset($data['profusion_col3_row1'])? $data['profusion_col3_row1']:0,
            'profusion_col3_row2'=>isset($data['profusion_col3_row2'])? $data['profusion_col3_row2']:0,
            'formatamanio_primario_p'=>isset($data['formatamanio_primario_p'])? $data['formatamanio_primario_p']:0,
            'formatamanio_primario_q'=>isset($data['formatamanio_primario_q'])? $data['formatamanio_primario_q']:0,
            'formatamanio_primario_r'=>isset($data['formatamanio_primario_r'])? $data['formatamanio_primario_r']:0,
            'formatamanio_primario_s'=>isset($data['formatamanio_primario_s'])? $data['formatamanio_primario_s']:0,
            'formatamanio_primario_t'=>isset($data['formatamanio_primario_t'])? $data['formatamanio_primario_t']:0,
            'formatamanio_primario_u'=>isset($data['formatamanio_primario_u'])? $data['formatamanio_primario_u']:0,
            'formatamanio_secundario_p'=>isset($data['formatamanio_secundario_p'])? $data['formatamanio_secundario_p']:0,
            'formatamanio_secundario_q'=>isset($data['formatamanio_secundario_q'])? $data['formatamanio_secundario_q']:0,
            'formatamanio_secundario_r'=>isset($data['formatamanio_secundario_r'])? $data['formatamanio_secundario_r']:0,
            'formatamanio_secundario_s'=>isset($data['formatamanio_secundario_s'])? $data['formatamanio_secundario_s']:0,
            'formatamanio_secundario_t'=>isset($data['formatamanio_secundario_t'])? $data['formatamanio_secundario_t']:0,
            'formatamanio_secundario_u'=>isset($data['formatamanio_secundario_u'])? $data['formatamanio_secundario_u']:0,
            'opacidad_0'=>isset($data['opacidad_0'])? $data['opacidad_0']:0,
            'opacidad_A'=>isset($data['opacidad_A'])? $data['opacidad_A']:0,
            'opacidad_B'=>isset($data['opacidad_B'])? $data['opacidad_B']:0,
            'opacidad_C'=>isset($data['opacidad_C'])? $data['opacidad_C']:0,
            'sitio_pared_toraxica_0'=>isset($data['sitio_pared_toraxica_0'])? $data['sitio_pared_toraxica_0']:0,
            'sitio_pared_toraxica_D'=>isset($data['sitio_pared_toraxica_D'])? $data['sitio_pared_toraxica_D']:0,
            'sitio_pared_toraxica_I'=>isset($data['sitio_pared_toraxica_I'])? $data['sitio_pared_toraxica_I']:0,
            'sitio_defrente_0'=>isset($data['sitio_defrente_0'])? $data['sitio_defrente_0']:0,
            'sitio_defrente_D'=>isset($data['sitio_defrente_D'])? $data['sitio_defrente_D']:0,
            'sitio_defrente_I'=>isset($data['sitio_defrente_I'])? $data['sitio_defrente_I']:0,
            'sitio_diafragma_0'=>isset($data['sitio_diafragma_0'])? $data['sitio_diafragma_0']:0,
            'sitio_diafragma_D'=>isset($data['sitio_diafragma_D'])? $data['sitio_diafragma_D']:0,
            'sitio_diafragma_I'=>isset($data['sitio_diafragma_I'])? $data['sitio_diafragma_I']:0,
            'sitio_otros_0'=>isset($data['sitio_otros_0'])? $data['sitio_otros_0']:0,
            'sitio_otros_D'=>isset($data['sitio_otros_D'])? $data['sitio_otros_D']:0,
            'sitio_otros_I'=>isset($data['sitio_otros_I'])? $data['sitio_otros_I']:0,
            'clasificacion_pared_toraxica_0'=>isset($data['clasificacion_pared_toraxica_0'])? $data['clasificacion_pared_toraxica_0']:0,
            'clasificacion_pared_toraxica_D'=>isset($data['clasificacion_pared_toraxica_D'])? $data['clasificacion_pared_toraxica_D']:0,
            'clasificacion_pared_toraxica_I'=>isset($data['clasificacion_pared_toraxica_I'])? $data['clasificacion_pared_toraxica_I']:0,
            'clasificacion_defrente_0'=>isset($data['clasificacion_defrente_0'])? $data['clasificacion_defrente_0']:0,
            'clasificacion_defrente_D'=>isset($data['clasificacion_defrente_D'])? $data['clasificacion_defrente_D']:0,
            'clasificacion_defrente_I'=>isset($data['clasificacion_defrente_I'])? $data['clasificacion_defrente_I']:0,
            'clasificacion_diafragma_0'=>isset($data['clasificacion_diafragma_0'])? $data['clasificacion_diafragma_0']:0,
            'clasificacion_diafragma_D'=>isset($data['clasificacion_diafragma_D'])? $data['clasificacion_diafragma_D']:0,
            'clasificacion_diafragma_I'=>isset($data['clasificacion_diafragma_I'])? $data['clasificacion_diafragma_I']:0,
            'clasificacion_otros_0'=>isset($data['clasificacion_otros_0'])? $data['clasificacion_otros_0']:0,
            'clasificacion_otros_D'=>isset($data['clasificacion_otros_D'])? $data['clasificacion_otros_D']:0,
            'clasificacion_otros_I'=>isset($data['clasificacion_otros_I'])? $data['clasificacion_otros_I']:0,
            'extencion_col1_row1'=>isset($data['extencion_col1_row1'])? $data['extencion_col1_row1']:0,
            'extencion_col3_row1'=>isset($data['extencion_col3_row1'])? $data['extencion_col3_row1']:0,
            'extencion_col1_row2'=>isset($data['extencion_col1_row2'])? $data['extencion_col1_row2']:0,
            'extencion_col2_row2'=>isset($data['extencion_col2_row2'])? $data['extencion_col2_row2']:0,
            'extencion_col3_row2'=>isset($data['extencion_col3_row2'])? $data['extencion_col3_row2']:0,
            'extencion_col4_row1'=>isset($data['extencion_col4_row1'])? $data['extencion_col4_row1']:0,
            'extencion_col6_row1'=>isset($data['extencion_col6_row1'])? $data['extencion_col6_row1']:0,
            'extencion_col4_row2'=>isset($data['extencion_col4_row2'])? $data['extencion_col4_row2']:0,
            'extencion_col5_row2'=>isset($data['extencion_col5_row2'])? $data['extencion_col5_row2']:0,
            'extencion_col6_row2'=>isset($data['extencion_col6_row2'])? $data['extencion_col6_row2']:0,
            'ancho_col1_row1'=>isset($data['ancho_col1_row1'])? $data['ancho_col1_row1']:0,
            'ancho_col1_row2'=>isset($data['ancho_col1_row2'])? $data['ancho_col1_row2']:0,
            'ancho_col2_row2'=>isset($data['ancho_col2_row2'])? $data['ancho_col2_row2']:0,
            'ancho_col3_row2'=>isset($data['ancho_col3_row2'])? $data['ancho_col3_row2']:0,
            'ancho_col2_row1'=>isset($data['ancho_col2_row1'])? $data['ancho_col2_row1']:0,
            'ancho_col4_row2'=>isset($data['ancho_col4_row2'])? $data['ancho_col4_row2']:0,
            'ancho_col5_row2'=>isset($data['ancho_col5_row2'])? $data['ancho_col5_row2']:0,
            'ancho_col6_row2'=>isset($data['ancho_col6_row2'])? $data['ancho_col6_row2']:0,
            'angulo_costofrenico_0'=>isset($data['angulo_costofrenico_0'])? $data['angulo_costofrenico_0']:0,
            'angulo_costofrenico_D'=>isset($data['angulo_costofrenico_D'])? $data['angulo_costofrenico_D']:0,
            'angulo_costofrenico_I'=>isset($data['angulo_costofrenico_I'])? $data['angulo_costofrenico_I']:0,
            'pared_toraxica_perfil_0'=>isset($data['pared_toraxica_perfil_0'])? $data['pared_toraxica_perfil_0']:0,
            'pared_toraxica_perfil_D'=>isset($data['pared_toraxica_perfil_D'])? $data['pared_toraxica_perfil_D']:0,
            'pared_toraxica_perfil_I'=>isset($data['pared_toraxica_perfil_I'])? $data['pared_toraxica_perfil_I']:0,
            'pared_toraxica_frente_0'=>isset($data['pared_toraxica_frente_0'])? $data['pared_toraxica_frente_0']:0,
            'pared_toraxica_frente_D'=>isset($data['pared_toraxica_frente_D'])? $data['pared_toraxica_frente_D']:0,
            'pared_toraxica_frente_I'=>isset($data['pared_toraxica_frente_I'])? $data['pared_toraxica_frente_I']:0,
            'clasificacion_perfil_0'=>isset($data['clasificacion_perfil_0'])? $data['clasificacion_perfil_0']:0,
            'clasificacion_perfil_D'=>isset($data['clasificacion_perfil_D'])? $data['clasificacion_perfil_D']:0,
            'clasificacion_perfil_I'=>isset($data['clasificacion_perfil_I'])? $data['clasificacion_perfil_I']:0,
            'clasificacion_frente_0'=>isset($data['clasificacion_frente_0'])? $data['clasificacion_frente_0']:0,
            'clasificacion_frente_D'=>isset($data['clasificacion_frente_D'])? $data['clasificacion_frente_D']:0,
            'clasificacion_frente_I'=>isset($data['clasificacion_frente_I'])? $data['clasificacion_frente_I']:0,
            'extencion2_col1_row1'=>isset($data['extencion2_col1_row1'])? $data['extencion2_col1_row1']:0,
            'extencion2_col3_row1'=>isset($data['extencion2_col3_row1'])? $data['extencion2_col3_row1']:0,
            'extencion2_col1_row2'=>isset($data['extencion2_col1_row2'])? $data['extencion2_col1_row2']:0,
            'extencion2_col2_row2'=>isset($data['extencion2_col2_row2'])? $data['extencion2_col2_row2']:0,
            'extencion2_col3_row2'=>isset($data['extencion2_col3_row2'])? $data['extencion2_col3_row2']:0,
            'extencion2_col4_row1'=>isset($data['extencion2_col4_row1'])? $data['extencion2_col4_row1']:0,
            'extencion2_col6_row1'=>isset($data['extencion2_col6_row1'])? $data['extencion2_col6_row1']:0,
            'extencion2_col4_row2'=>isset($data['extencion2_col4_row2'])? $data['extencion2_col4_row2']:0,
            'extencion2_col5_row2'=>isset($data['extencion2_col5_row2'])? $data['extencion2_col5_row2']:0,
            'extencion2_col6_row2'=>isset($data['extencion2_col6_row2'])? $data['extencion2_col6_row2']:0,
            'ancho2_col1_row1'=>isset($data['ancho2_col1_row1'])? $data['ancho2_col1_row1']:0,
            'ancho2_col1_row2'=>isset($data['ancho2_col1_row2'])? $data['ancho2_col1_row2']:0,
            'ancho2_col2_row2'=>isset($data['ancho2_col2_row2'])? $data['ancho2_col2_row2']:0,
            'ancho2_col3_row2'=>isset($data['ancho2_col3_row2'])? $data['ancho2_col3_row2']:0,
            'ancho2_col2_row1'=>isset($data['ancho2_col2_row1'])? $data['ancho2_col2_row1']:0,
            'ancho2_col4_row2'=>isset($data['ancho2_col4_row2'])? $data['ancho2_col4_row2']:0,
            'ancho2_col5_row2'=>isset($data['ancho2_col5_row2'])? $data['ancho2_col5_row2']:0,
            'ancho2_col6_row2'=>isset($data['ancho2_col6_row2'])? $data['ancho2_col6_row2']:0,
            'simbolo_estado'=>isset($data['simbolo_estado'])? $data['simbolo_estado']:0,
            'simbolo_col1_row1'=>isset($data['simbolo_col1_row1'])? $data['simbolo_col1_row1']:0,
            'simbolo_col1_row2'=>isset($data['simbolo_col1_row2'])? $data['simbolo_col1_row2']:0,
            'simbolo_col1_row3'=>isset($data['simbolo_col1_row3'])? $data['simbolo_col1_row3']:0,
            'simbolo_col1_row4'=>isset($data['simbolo_col1_row4'])? $data['simbolo_col1_row4']:0,
            'simbolo_col1_row5'=>isset($data['simbolo_col1_row5'])? $data['simbolo_col1_row5']:0,
            'simbolo_col1_row6'=>isset($data['simbolo_col1_row6'])? $data['simbolo_col1_row6']:0,
            'simbolo_col1_row7'=>isset($data['simbolo_col1_row7'])? $data['simbolo_col1_row7']:0,
            'simbolo_col1_row8'=>isset($data['simbolo_col1_row8'])? $data['simbolo_col1_row8']:0,
            'simbolo_col1_row9'=>isset($data['simbolo_col1_row9'])? $data['simbolo_col1_row9']:0,
            'simbolo_col1_row10'=>isset($data['simbolo_col1_row10'])? $data['simbolo_col1_row10']:0,
            'simbolo_col1_row11'=>isset($data['simbolo_col1_row11'])? $data['simbolo_col1_row11']:0,
            'simbolo_col1_row12'=>isset($data['simbolo_col1_row12'])? $data['simbolo_col1_row12']:0,
            'simbolo_col1_row13'=>isset($data['simbolo_col1_row13'])? $data['simbolo_col1_row13']:0,
            'simbolo_col1_row14'=>isset($data['simbolo_col1_row14'])? $data['simbolo_col1_row14']:0,
            'simbolo_col1_row15'=>isset($data['simbolo_col1_row15'])? $data['simbolo_col1_row15']:0,
            'simbolo_col2_row1'=>isset($data['simbolo_col2_row1'])? $data['simbolo_col2_row1']:0,
            'simbolo_col2_row2'=>isset($data['simbolo_col2_row2'])? $data['simbolo_col2_row2']:0,
            'simbolo_col2_row3'=>isset($data['simbolo_col2_row3'])? $data['simbolo_col2_row3']:0,
            'simbolo_col2_row4'=>isset($data['simbolo_col2_row4'])? $data['simbolo_col2_row4']:0,
            'simbolo_col2_row5'=>isset($data['simbolo_col2_row5'])? $data['simbolo_col2_row5']:0,
            'simbolo_col2_row6'=>isset($data['simbolo_col2_row6'])? $data['simbolo_col2_row6']:0,
            'simbolo_col2_row7'=>isset($data['simbolo_col2_row7'])? $data['simbolo_col2_row7']:0,
            'simbolo_col2_row8'=>isset($data['simbolo_col2_row8'])? $data['simbolo_col2_row8']:0,
            'simbolo_col2_row9'=>isset($data['simbolo_col2_row9'])? $data['simbolo_col2_row9']:0,
            'simbolo_col2_row10'=>isset($data['simbolo_col2_row10'])? $data['simbolo_col2_row10']:0,
            'simbolo_col2_row11'=>isset($data['simbolo_col2_row11'])? $data['simbolo_col2_row11']:0,
            'simbolo_col2_row12'=>isset($data['simbolo_col2_row12'])? $data['simbolo_col2_row12']:0,
            'simbolo_col2_row13'=>isset($data['simbolo_col2_row13'])? $data['simbolo_col2_row13']:0,
            'simbolo_col2_row14'=>isset($data['simbolo_col2_row14'])? $data['simbolo_col2_row14']:0,
            'torax_conclusion'=>isset($data['torax_conclusion'])? $data['torax_conclusion']:null,
            'vertices'=>isset($data['vertices'])? $data['vertices']:null,
            'campos_pulmonares'=>isset($data['campos_pulmonares'])? $data['campos_pulmonares']:null,
            'hilos'=>isset($data['hilos'])? $data['hilos']:null,
            'senos'=>isset($data['senos'])? $data['senos']:null,
            'mediastinos'=>isset($data['mediastinos'])? $data['mediastinos']:null,
            'siluete_cardiaca'=>isset($data['siluete_cardiaca'])? $data['siluete_cardiaca']:null,
            'diafragma'=>isset($data['diafragma'])? $data['diafragma']:null,
            'kb'=>isset($data['kb'])? $data['kb']:null,
            'tiempo'=>isset($data['tiempo'])? $data['tiempo']:null,
            'amperaje'=>isset($data['amperaje'])? $data['amperaje']:null,
            'diametro_torax'=>isset($data['diametro_torax'])? $data['diametro_torax']:null,
           // 'fecha_registro'=>Carbon::now(),
           // 'lista_examen_id'=>isset($data['lista_examen_id'])? $data['lista_examen_id']:null,
           // 'cita_id'=>isset($data['cita_id'])? $data['cita_id']:null,
           // 'estado'=>true
           'user_id'=>Auth::user()->id;
          ]);
          return response()->json(['mensaje' =>"registro exitoso"]);
      }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Torax  $torax
     * @return \Illuminate\Http\Response
     */
    public function destroy(Torax $torax)
    {
        //
    }

    public function reportetorax($id)
    {
      $cita=Cita::find($id);
      $view=View::make('evaluacionmedica.reportes.evaluaciontorax',compact('cita'));
      $pdf = \App::make('dompdf.wrapper');
      $pdf->loadHTML($view);
      $pdf->stream($view);
      return $pdf->stream();
    }

}
